// Write QuantLib reference values for every test grid to CSV (fixtures/quantlib/*.csv),
// so other implementations (the Rust library, the WASM harness) can use the same golden
// vectors without linking QuantLib.   Usage: export_fixtures <output-dir>
#include <ql/pricingengines/blackformula.hpp>
#include <ql/termstructures/volatility/sabr.hpp>
#include <ql/termstructures/volatility/zabr.hpp>
#include <ql/version.hpp>

#include <charconv>
#include <cstdio>
#include <initializer_list>
#include <filesystem>
#include <fstream>
#include <string>

#include "../tests/common.hpp"

namespace {

/// Shortest decimal that round-trips to the same double (exact, and readable).
std::string num(double x) {
    char buf[64];
    auto r = std::to_chars(buf, buf + sizeof buf, x);
    return std::string(buf, r.ptr);
}

void row(std::ofstream& out, std::initializer_list<double> values) {
    bool first = true;
    for (double v : values) {
        out << (first ? "" : ",") << num(v);
        first = false;
    }
    out << '\n';
}

std::ofstream open(const std::filesystem::path& dir, const std::string& name,
                   const std::string& header) {
    std::ofstream out(dir / name);
    out << "# QuantLib " << QL_VERSION << " (commit 0191ca7); generated by "
        << "quantlib-conformance/tools/export_fixtures\n" << header << "\n";
    return out;
}

}  // namespace

int main(int argc, char** argv) {
    const std::filesystem::path dir = argc > 1 ? argv[1] : "fixtures/quantlib";
    std::filesystem::create_directories(dir);
    {
        auto o = open(dir, "black76.csv", "F,K,s,t,r,displacement,call,put,intrinsic");
        for (double d : grids::displacements())
            for (auto c : grids::black()) {
                const double sd = c.s * std::sqrt(c.t), df = std::exp(-c.r * c.t);
                row(o, {c.F, c.K, c.s, c.t, c.r, d,
                        ql::blackFormula(ql::Option::Call, c.K, c.F, sd, df, d),
                        ql::blackFormula(ql::Option::Put, c.K, c.F, sd, df, d),
                        ql::blackFormula(ql::Option::Call, c.K, c.F, 0.0, df, d)});
            }
    }
    {
        auto o = open(dir, "bachelier.csv", "F,K,sigma,T,call,put");
        for (auto c : grids::bachelier()) {
            const double sd = c.sigma * std::sqrt(c.T);
            row(o, {c.F, c.K, c.sigma, c.T,
                    ql::bachelierBlackFormula(ql::Option::Call, c.K, c.F, sd, 1.0),
                    ql::bachelierBlackFormula(ql::Option::Put, c.K, c.F, sd, 1.0)});
        }
    }
    {
        auto o = open(dir, "sabr.csv", "f,K,alpha,beta,nu,rho,T,shift,lognormal_vol,normal_vol");
        for (double d : grids::displacements())
            for (auto c : grids::sabr())
                row(o, {c.f, c.K, c.alpha, c.beta, c.nu, c.rho, c.T, d,
                        ql::shiftedSabrVolatility(c.K, c.f, c.T, c.alpha, c.beta, c.nu, c.rho, d),
                        ql::shiftedSabrVolatility(c.K, c.f, c.T, c.alpha, c.beta, c.nu, c.rho, d,
                                                  ql::VolatilityType::Normal)});
    }
    {
        auto o = open(dir, "heston.csv", "S,v0,kappa,theta,sigma,rho,r,q,K,T,call");
        for (auto c : grids::heston())
            row(o, {c.S, c.v, c.kappa, c.theta, c.sigma, c.rho, c.r, 0.0, c.K, c.T,
                    qlsetup::heston_call(c)});
    }
    {
        auto o = open(dir, "bates.csv",
                      "S,V0,T,b,r,X,lambda,kbar,delta,alpha,betastar,sigma_v,rho,call");
        for (auto c : grids::bates())
            row(o, {c.S, c.V, c.T, c.b, c.r, c.X, c.lambda, c.kbar, c.delta, c.alpha, c.betastar,
                    c.sigma_v, c.rho, qlsetup::bates_call(c)});
    }
    {
        auto o = open(dir, "zabr.csv", "f,K,alpha,beta,nu,rho,gamma,T,normal_vol");
        for (auto c : grids::zabr()) {
            ql::ZabrModel m(c.T, c.f, c.alpha, c.beta, c.nu, c.rho, c.gamma);
            row(o, {c.f, c.K, c.alpha, c.beta, c.nu, c.rho, c.gamma, c.T,
                    m.normalVolatility(c.K)});
        }
    }
    std::printf("wrote QuantLib %s fixtures to %s\n", QL_VERSION, dir.string().c_str());
    return 0;
}
