"""Generate include/wwmath/generated/formulas.hpp from the paper ASTs.

The WWMath side of every conformance test is C++ emitted from research/papers/*.toml by
research/tools/cpp.py; nothing in it is hand-written or taken from QuantLib.

    python quantlib-conformance/tools/generate.py
"""
from __future__ import annotations

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)
ROOT = os.path.dirname(PROJECT)
sys.path.insert(0, os.path.join(ROOT, "research", "tools"))

import cpp  # noqa: E402
from validate import Library  # noqa: E402

# Formula ids to emit, in the order they appear in the header.
TARGETS = [
    "black1976.call", "black1976.put", "black1976.intrinsic",
    "bachelier1900.call", "bachelier1900.put",
    "hagan2002.sigma_B", "hagan2002.sigma_ATM",
    "heston1993.call", "heston1993.call_trap",
    "bates1996.call",
    "zabr.sabr_v", "zabr.sabr_vbar", "zabr.zabr_y", "zabr.F",
]


def main() -> int:
    lib = Library()
    parts = ["// GENERATED by quantlib-conformance/tools/generate.py from research/papers/*.toml.",
             "// Do not edit: change the paper TOML (or research/tools/cpp.py) and regenerate.",
             "// Each function is the right-hand side of one paper formula; argument names are",
             "// the paper's symbols, in the order the paper's [[symbols]] table declares them.",
             "#pragma once", "", "#include <cmath>", "#include <complex>", "",
             '#include "wwmath/runtime.hpp"', "", "namespace wwmath::gen {", ""]
    for fid in TARGETS:
        paper = lib.formula_owner[fid]
        order = list(paper.symbols)
        parts.append(cpp.emit_function(fid, paper.formulas[fid], paper.defs, order))
    parts.append("}  // namespace wwmath::gen")
    out = os.path.join(PROJECT, "include", "wwmath", "generated", "formulas.hpp")
    with open(out, "w") as fh:
        fh.write("\n".join(parts) + "\n")
    print(f"wrote {os.path.relpath(out, ROOT)} ({len(TARGETS)} functions)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
