"""Authoring source for research/papers/*.toml.

Formulas are written with the small DSL in ``mathast`` and emitted as TOML with
the Math AST embedded as JSON. The TOML files are the library; this script only
makes writing deep ASTs by hand less error-prone. Re-run after editing:

    python research/tools/author_papers.py && python research/tools/validate.py
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

from mathast import (  # noqa: E402
    I, INF, PI, add, apply, approx, call, const, d, def_key, distributed, div, eq, exp,
    expect, idx, integral, latex, log, mul, neg, num, pow_, sde, sqrt, sub, sym, to_json,
)

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
N = lambda x: call("N", x)  # noqa: E731
n = lambda x: call("n", x)  # noqa: E731
Re = lambda x: call("Re", x)  # noqa: E731
mx = lambda a, b: call("max", a, b)  # noqa: E731
half = div(1, 2)


# ---------------------------------------------------------------------------
# TOML emission
# ---------------------------------------------------------------------------

def q(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def val(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return q(v)
    if isinstance(v, list):
        return "[" + ", ".join(val(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{ " + ", ".join(f"{k} = {val(x)}" for k, x in v.items()) + " }"
    raise TypeError(v)


def ml(s: str) -> str:
    assert "'''" not in s
    return "'''\n" + s + "\n'''"


def emit(paper: dict) -> str:
    out = ["# Generated by research/tools/author_papers.py -- Math AST library entry.",
           "# ast fields hold canonical Math AST as JSON (see research/schema/math_ast.md).",
           "schema_version = 1", "", "[paper]"]
    for k, v in paper["paper"].items():
        out.append(f"{k} = {val(v)}")
    for s in paper["symbols"]:
        out += ["", "[[symbols]]"] + [f"{k} = {val(v)}" for k, v in s.items()]
    defs = {def_key(f["ast"]["args"][0]) for f in paper["formulas"]
            if f["ast"]["op"] in ("Eq", "Approx")}
    for f in paper["formulas"]:
        ast = f.pop("ast")
        from mathast import free_symbols
        is_def = ast["op"] in ("Eq", "Approx")
        own = def_key(ast["args"][0]) if is_def else None
        used = free_symbols(ast["args"][1] if is_def else ast)
        deps = sorted(k for k in defs if k and k != own and k.split("[")[0].split("(")[0] in used)
        out += ["", "[[formulas]]"]
        for k, v in f.items():
            out.append(f"{k} = {val(v)}")
        if deps:
            out.append(f"depends_on = {val(deps)}")
        out.append(f"latex = {ml(latex(ast))}")
        out.append(f"ast = {ml(to_json(ast))}")
    for c in paper.get("checks", []):
        out += ["", "[[checks]]"]
        for k, v in c.items():
            if k.endswith("_ast"):
                out.append(f"{k} = {ml(to_json(v))}")
            elif k == "bind":
                out.append("bind = { " + ", ".join(
                    f"{b} = {ml(to_json(x)) if isinstance(x, dict) else q(x)}"
                    for b, x in v.items()) + " }")
            else:
                out.append(f"{k} = {val(v)}")
    return "\n".join(out) + "\n"


def S(name, kind, desc, **kw):
    return {"name": name, "kind": kind, "description": desc, **kw}


def F(id_, name, kind, ast, source, **kw):
    return {"id": id_, "name": name, "kind": kind, "source": source, **kw, "ast": ast}


def src(equation=None, page=None, fidelity="verbatim-notation", verified=False, ref=None):
    s = {}
    if ref:
        s["reference"] = ref
    if equation:
        s["equation"] = equation
    if page:
        s["page"] = page
    s["fidelity"] = fidelity
    s["verified_against_pdf"] = verified
    return s


# ---------------------------------------------------------------------------
# Bachelier 1900
# ---------------------------------------------------------------------------

def bachelier():
    x, t, k = sym("x"), sym("t"), sym("k")
    Fw, K, sg, T = sym("F"), sym("K"), sym("sigma"), sym("T")
    dd = sym("d")
    return {
        "paper": {"id": "bachelier1900", "short": "Bachelier 1900",
                  "transcription_status": "core-complete"},
        "symbols": [
            S("x", "variable", "Deviation of the price from its current (true) value"),
            S("t", "time", "Elapsed time"),
            S("k", "parameter", "Bachelier's 'coefficient of instability' (volatility scale)",
              domain="positive"),
            S("F", "variable", "Forward / current price (modern restatement)"),
            S("K", "parameter", "Strike"),
            S("sigma", "parameter", "Normal (absolute) volatility; sigma = k*sqrt(2*pi)",
              domain="positive"),
            S("T", "time", "Time to expiry"),
            S("z", "integration_variable", "Standard normal integration variable"),
        ],
        "formulas": [
            F("bachelier1900.density", "Probability density of the price deviation",
              "density",
              eq(apply("p", x, t), mul(div(1, mul(2, PI, k, sqrt(t))),
                                        exp(neg(div(pow_(x, 2), mul(4, PI, pow_(k, 2), t)))))),
              src(fidelity="verbatim-notation"),
              notes="Gaussian with variance 2*pi*k^2*t: the first mathematical Brownian motion."),
            F("bachelier1900.simple_option_value", "Value of the simple (at-the-money) option",
              "price", eq(sym("a"), mul(k, sqrt(t))),
              src(fidelity="restated"),
              notes="Bachelier shows the simple option's value grows like sqrt(t); with his "
                    "density the constant is exactly k (checked below)."),
            F("bachelier1900.call", "Normal-model call price (modern restatement)", "price",
              eq(sym("C"), add(mul(sub(Fw, K), N(dd)), mul(sg, sqrt(T), n(dd)))),
              src(fidelity="modern-restatement",
                  ref="Schachermayer & Teichmann (2008), Math. Finance 18(1)")),
            F("bachelier1900.put", "Normal-model put price (modern restatement)", "price",
              eq(sym("P"), add(mul(sub(K, Fw), N(neg(dd))), mul(sg, sqrt(T), n(dd)))),
              src(fidelity="modern-restatement")),
            F("bachelier1900.d", "Normalised moneyness", "definition",
              eq(dd, div(sub(Fw, K), mul(sg, sqrt(T)))), src(fidelity="modern-restatement")),
        ],
        "checks": [
            {"id": "density-normalised", "kind": "value",
             "description": "Bachelier's density integrates to one",
             "target_ast": integral(apply("p", sym("x"), t), "x", neg(INF), INF),
             "inputs": {"k": 0.8, "t": 2.0}, "expected": 1.0, "rel_tol": 1e-9},
            {"id": "simple-option-from-density", "kind": "compare",
             "description": "a = k sqrt(t) equals the positive expectation of x under p",
             "target_ast": integral(mul(x, apply("p", x, t)), "x", 0, INF),
             "against": "bachelier1900.simple_option_value",
             "inputs": {"k": 0.8, "t": 2.0}, "rel_tol": 1e-8},
            {"id": "call-vs-payoff-integral", "kind": "compare",
             "description": "Closed form equals E[(F + sigma sqrt(T) Z - K)^+]",
             "target": "bachelier1900.call",
             "against_ast": integral(mul(mx(sub(add(Fw, mul(sg, sqrt(T), sym("z"))), K), 0),
                                         n(sym("z"))), "z", neg(INF), INF),
             "inputs": {"F": 100.0, "K": 103.0, "sigma": 12.0, "T": 0.75}, "rel_tol": 1e-7},
            {"id": "put-call-parity", "kind": "compare", "description": "C - P = F - K",
             "target_ast": sub(sym("C"), sym("P")), "against_ast": sub(Fw, K),
             "inputs": {"F": 100.0, "K": 91.0, "sigma": 9.0, "T": 1.5}, "rel_tol": 1e-12},
            {"id": "modern-vs-1900-atm", "kind": "compare",
             "description": "Modern ATM call with sigma = k sqrt(2 pi) equals Bachelier's a = k sqrt(t)",
             "target": "bachelier1900.call", "against": "bachelier1900.simple_option_value",
             "bind": {"sigma": mul(k, sqrt(mul(2, PI)))},
             "inputs": {"F": 100.0, "K": 100.0, "k": 3.0, "T": 0.5, "t": 0.5}, "rel_tol": 1e-12},
            {"id": "monte-carlo", "kind": "monte_carlo",
             "description": "Euler simulation of dF = sigma dW reproduces the call price",
             "sde": ["bachelier1900.sde"], "time": "t", "horizon": "T",
             "payoff_ast": mx(sub(Fw, K), 0), "against": "bachelier1900.call",
             "inputs": {"F": 100.0, "K": 104.0, "sigma": 10.0, "T": 1.0},
             "paths": 200000, "steps": 20, "seed": 1, "abs_tol": 0.0},
        ],
        "extra_formulas": [
            F("bachelier1900.sde", "Arithmetic Brownian motion (modern restatement)", "sde",
              sde(Fw, (sg, sym("W"))), src(fidelity="modern-restatement")),
        ],
        "extra_symbols": [S("W", "brownian_motion", "Standard Brownian motion")],
    }


# ---------------------------------------------------------------------------
# Black 1976
# ---------------------------------------------------------------------------

def black():
    Fw, c_, s, t, r = sym("F"), sym("cstar"), sym("s"), sym("t"), sym("r")
    d1, d2 = sym("d_1"), sym("d_2")
    return {
        "paper": {"id": "black1976", "short": "Black 1976", "transcription_status": "core-complete"},
        "symbols": [
            S("F", "state", "Futures price", domain="positive"),
            S("cstar", "parameter", "Exercise price (Black writes c*)"),
            S("s", "parameter", "Volatility: s^2 is the variance rate of dF/F", domain="positive"),
            S("t", "time", "Time to maturity"),
            S("r", "parameter", "Continuously compounded interest rate"),
            S("z", "brownian_motion", "Standard Brownian motion"),
            S("tau", "time", "Calendar time along simulated paths"),
            S("T", "time", "Horizon used by the Monte Carlo check"),
            S("y", "integration_variable", "Standard normal integration variable"),
        ],
        "formulas": [
            F("black1976.sde", "Lognormal futures dynamics (restated)", "sde",
              sde(Fw, (mul(s, Fw), sym("z"))), src(fidelity="restated"),
              notes="Driftless under the pricing measure; time variable tau."),
            F("black1976.call", "Call on a futures contract", "price",
              eq(sym("c"), mul(exp(mul(neg(r), t)), sub(mul(Fw, N(d1)), mul(c_, N(d2))))),
              src()),
            F("black1976.d_1", "d1", "definition",
              eq(d1, div(add(log(div(Fw, c_)), mul(div(pow_(s, 2), 2), t)), mul(s, sqrt(t)))),
              src()),
            F("black1976.d_2", "d2", "definition", eq(d2, sub(d1, mul(s, sqrt(t)))), src()),
            F("black1976.put", "Put on a futures contract (via parity)", "price",
              eq(sym("p"), mul(exp(mul(neg(r), t)),
                               sub(mul(c_, N(neg(d2))), mul(Fw, N(neg(d1)))))),
              src(fidelity="derived")),
        ],
        "checks": [
            {"id": "put-call-parity", "kind": "compare", "description": "c - p = e^{-rt}(F - c*)",
             "target_ast": sub(sym("c"), sym("p")),
             "against_ast": mul(exp(mul(neg(r), t)), sub(Fw, c_)),
             "inputs": {"F": 100.0, "cstar": 95.0, "s": 0.25, "t": 0.8, "r": 0.03},
             "rel_tol": 1e-12},
            {"id": "call-vs-lognormal-integral", "kind": "compare",
             "description": "Closed form equals discounted E[(F_T - c*)^+] under the lognormal law",
             "target": "black1976.call",
             "against_ast": mul(exp(mul(neg(r), t)), integral(
                 mul(mx(sub(mul(Fw, exp(add(neg(mul(div(pow_(s, 2), 2), t)),
                                            mul(s, sqrt(t), sym("y"))))), c_), 0), n(sym("y"))),
                 "y", neg(INF), INF)),
             "inputs": {"F": 100.0, "cstar": 110.0, "s": 0.3, "t": 1.25, "r": 0.02},
             "rel_tol": 1e-7},
            {"id": "monte-carlo", "kind": "monte_carlo",
             "description": "Euler simulation of dF = s F dz reproduces the call price",
             "sde": ["black1976.sde"], "time": "tau", "horizon": "t",
             "payoff_ast": mul(exp(mul(neg(r), t)), mx(sub(Fw, c_), 0)),
             "against": "black1976.call",
             "inputs": {"F": 100.0, "cstar": 105.0, "s": 0.2, "t": 1.0, "r": 0.01},
             "paths": 200000, "steps": 200, "seed": 2, "abs_tol": 0.02},
        ],
    }


# ---------------------------------------------------------------------------
# Heston 1993
# ---------------------------------------------------------------------------

def heston():
    Sx, v, t = sym("S"), sym("v"), sym("t")
    mu, kap, th, sg, rho, lam = (sym(x) for x in ("mu", "kappa", "theta", "sigma", "rho", "lambda"))
    K, r, tau, phi, j, x = sym("K"), sym("r"), sym("tau"), sym("phi"), sym("j"), sym("x")
    a = sym("a")
    bj, uj, dj, gj = idx("b", j), idx("u", j), idx("d", j), idx("g", j)
    rsp = mul(rho, sg, phi, I)  # rho sigma phi i

    def trap(name_c, name_d, name_g, name_f, sign):
        """Heston's original form (sign=+1) or Albrecher et al. 'little trap' form (sign=-1)."""
        dd = dj if sign > 0 else neg(dj)
        core = add(sub(bj, rsp), dd)                     # b_j - rho sigma phi i +/- d_j
        other = sub(sub(bj, rsp), dd)
        g = idx(name_g, j)
        edt = exp(mul(dd, tau))
        return [
            eq(idx(name_c, j), add(mul(r, phi, I, tau), mul(div(a, pow_(sg, 2)), sub(
                mul(core, tau), mul(2, log(div(sub(1, mul(g, edt)), sub(1, g)))))))),
            eq(idx(name_d, j), mul(div(core, pow_(sg, 2)),
                                   div(sub(1, edt), sub(1, mul(g, edt))))),
            eq(g, div(core, other)),
            eq(idx(name_f, j), exp(add(idx(name_c, j), mul(idx(name_d, j), v), mul(I, phi, x)))),
        ]

    orig = trap("C", "D", "g", "f", +1)
    alt = trap("Ct", "Dt", "gt", "ft", -1)
    h = src
    alb = dict(fidelity="restated", ref="Albrecher, Mayer, Schoutens & Tistaert (2007), "
                                        "'The Little Heston Trap', Wilmott Magazine, Jan 2007")
    return {
        "paper": {"id": "heston1993", "short": "Heston 1993", "transcription_status": "core-complete",
                  "bib": ["heston1993", "albrecher2007"]},
        "symbols": [
            S("S", "state", "Spot asset price", domain="positive"),
            S("v", "state", "Instantaneous variance", domain="nonnegative"),
            S("t", "time", "Calendar time"),
            S("mu", "parameter", "Spot drift (set mu = r for risk-neutral simulation)"),
            S("kappa", "parameter", "Mean-reversion speed of variance"),
            S("theta", "parameter", "Long-run variance"),
            S("sigma", "parameter", "Volatility of volatility"),
            S("rho", "parameter", "Correlation between z_1 and z_2"),
            S("lambda", "parameter", "Price of volatility risk"),
            S("z_1", "brownian_motion", "Brownian motion driving the spot"),
            S("z_2", "brownian_motion", "Brownian motion driving the variance"),
            S("K", "parameter", "Strike"),
            S("r", "parameter", "Risk-free rate (constant)"),
            S("tau", "time", "Time to maturity, T - t"),
            S("phi", "integration_variable", "Fourier variable"),
            S("j", "index", "Probability index, j in {1, 2}"),
        ],
        "formulas": [
            F("heston1993.spot_sde", "Spot dynamics", "sde",
              sde(Sx, (mul(mu, Sx), t), (mul(sqrt(v), Sx), sym("z_1"))), h("(1)")),
            F("heston1993.variance_sde", "Variance dynamics (square-root process)", "sde",
              sde(v, (mul(kap, sub(th, v)), t), (mul(sg, sqrt(v)), sym("z_2"))), h("(4)")),
            F("heston1993.correlation", "Brownian correlation", "correlation",
              eq(mul(d(sym("z_1")), d(sym("z_2"))), mul(rho, d(t))), h()),
            F("heston1993.call", "European call price", "price",
              eq(sym("C"), sub(mul(Sx, idx("P", 1)), mul(K, sym("P_tT"), idx("P", 2)))), h("(10)")),
            F("heston1993.bond", "Discount bond price (constant rate)", "definition",
              eq(sym("P_tT"), exp(mul(neg(r), tau))), h(fidelity="restated")),
            F("heston1993.x", "Log spot", "definition", eq(x, log(Sx)), h()),
            F("heston1993.P_j", "In-the-money probabilities", "probability",
              eq(idx("P", j), add(half, mul(div(1, PI), integral(
                  Re(div(mul(exp(mul(neg(I), phi, log(K))), idx("f", j)), mul(I, phi))),
                  "phi", 0, INF)))), h("(18)")),
            F("heston1993.f_j", "Characteristic functions", "characteristic_function",
              orig[3], h("(17)")),
            F("heston1993.C_j", "C(tau; phi)", "definition", orig[0], h("(17)")),
            F("heston1993.D_j", "D(tau; phi)", "definition", orig[1], h("(17)")),
            F("heston1993.g_j", "g", "definition", orig[2], h("(17)")),
            F("heston1993.d_j", "d", "definition",
              eq(dj, sqrt(sub(pow_(sub(rsp, bj), 2),
                              mul(pow_(sg, 2), sub(mul(2, uj, phi, I), pow_(phi, 2)))))), h("(17)")),
            F("heston1993.u_1", "u_1", "definition", eq(idx("u", 1), half), h("(12)")),
            F("heston1993.u_2", "u_2", "definition", eq(idx("u", 2), neg(half)), h("(12)")),
            F("heston1993.a", "a", "definition", eq(a, mul(kap, th)), h("(12)")),
            F("heston1993.b_1", "b_1", "definition", eq(idx("b", 1), sub(add(kap, lam), mul(rho, sg))),
              h("(12)")),
            F("heston1993.b_2", "b_2", "definition", eq(idx("b", 2), add(kap, lam)), h("(12)")),
            F("heston1993.ft_j", "Characteristic functions, rotation-count-safe form",
              "characteristic_function", alt[3], h(**alb),
              notes="Algebraically equal to (17); continuous in phi for long maturities."),
            F("heston1993.Ct_j", "C(tau; phi), little-trap form", "definition", alt[0], h(**alb)),
            F("heston1993.Dt_j", "D(tau; phi), little-trap form", "definition", alt[1], h(**alb)),
            F("heston1993.gt_j", "g, little-trap form", "definition", alt[2], h(**alb)),
        ],
        "checks": [
            {"id": f"trap-form-agrees-{part}-{jj}", "kind": "compare",
             "description": f"{part} of f_{jj} equals the little-trap form at a sample phi",
             "target_ast": call(part, idx("f", jj)), "against_ast": call(part, idx("ft", jj)),
             "inputs": {"S": 100.0, "v": 0.04, "kappa": 1.5, "theta": 0.05, "sigma": 0.6,
                        "rho": -0.7, "lambda": 0.0, "K": 100.0, "r": 0.02, "tau": 0.5,
                        "phi": 1.7}, "abs_tol": 1e-12}
            for part in ("Re", "Im") for jj in (1, 2)
        ] + [
            {"id": "black-scholes-limit", "kind": "compare",
             "description": "Vol-of-vol -> 0 with v = theta recovers Black-Scholes (via Black 1976)",
             "target": "heston1993.call", "against": "black1976.call",
             "bind": {"F": mul(Sx, exp(mul(r, tau))), "s": sqrt(th)},
             "inputs": {"S": 100.0, "v": 0.04, "kappa": 2.0, "theta": 0.04, "sigma": 0.01,
                        "rho": 0.0, "lambda": 0.0, "K": 105.0, "r": 0.03, "tau": 1.0,
                        "cstar": 105.0, "t": 1.0}, "rel_tol": 2e-4},
            {"id": "monte-carlo", "kind": "monte_carlo",
             "description": "Euler (full truncation) simulation of the SDEs reproduces eq. (10)",
             "sde": ["heston1993.spot_sde", "heston1993.variance_sde"],
             "correlation": ["heston1993.correlation"], "time": "t", "horizon": "tau",
             "payoff_ast": mul(exp(mul(neg(r), tau)), mx(sub(Sx, K), 0)),
             "against": "heston1993.call",
             "inputs": {"S": 100.0, "v": 0.04, "kappa": 1.5, "theta": 0.05, "sigma": 0.5,
                        "rho": -0.7, "lambda": 0.0, "mu": 0.02, "K": 100.0, "r": 0.02,
                        "tau": 1.0}, "paths": 200000, "steps": 250, "seed": 3, "abs_tol": 0.03},
        ],
    }


# ---------------------------------------------------------------------------
# Bates 1996
# ---------------------------------------------------------------------------

def bates():
    Sx, V, t, T, X = sym("S"), sym("V"), sym("t"), sym("T"), sym("X")
    b, lam, kb, k = sym("b"), sym("lambdastar"), sym("kbarstar"), sym("k")
    al, be, sv, rho, de, r = (sym(x) for x in ("alpha", "betastar", "sigma_v", "rho", "delta", "r"))
    u, phi = sym("u"), sym("phi")
    iu = mul(I, u)
    core = sub(be, mul(rho, sv, iu))
    dd, gg = apply("d", u), apply("g", u)
    edT = exp(mul(neg(dd), T))
    rst = dict(fidelity="restated",
               ref="Bates (1996) model with the Heston CF in the Albrecher et al. (2007) form")
    return {
        "paper": {"id": "bates1996", "short": "Bates 1996", "transcription_status": "core-complete"},
        "symbols": [
            S("S", "state", "Spot exchange rate (DM price)", domain="positive"),
            S("V", "state", "Instantaneous variance", domain="nonnegative"),
            S("t", "time", "Calendar time"),
            S("T", "time", "Time to maturity"),
            S("X", "parameter", "Strike (Bates writes X)"),
            S("b", "parameter", "Cost of carry, r - r* for currencies"),
            S("r", "parameter", "Domestic interest rate"),
            S("lambdastar", "parameter", "Risk-neutral jump intensity"),
            S("kbarstar", "parameter", "Risk-neutral mean relative jump size"),
            S("k", "random_variable", "Random relative jump size"),
            S("q", "poisson_process", "Jump counter", intensity="lambdastar"),
            S("alpha", "parameter", "Variance drift intercept (alpha = kappa theta)"),
            S("betastar", "parameter", "Risk-neutral variance mean-reversion speed"),
            S("sigma_v", "parameter", "Volatility of variance"),
            S("rho", "parameter", "Correlation of Z and Z_v"),
            S("delta", "parameter", "Std. dev. of log jump size", domain="nonnegative"),
            S("Z", "brownian_motion", "Brownian motion driving S"),
            S("Z_v", "brownian_motion", "Brownian motion driving V"),
            S("u", "variable", "Characteristic-function argument"),
            S("phi", "integration_variable", "Fourier variable"),
        ],
        "formulas": [
            F("bates1996.spot_sde", "Risk-neutral spot dynamics (jump-diffusion)", "sde",
              sde(Sx, (mul(sub(b, mul(lam, kb)), Sx), t), (mul(sqrt(V), Sx), sym("Z")),
                  (mul(k, Sx), sym("q"))), src(fidelity="restated"),
              notes="Bates writes dS/S = (b - lambda* kbar*) dt + sqrt(V) dZ + k dq*; "
                    "multiplied through by S here."),
            F("bates1996.variance_sde", "Risk-neutral variance dynamics", "sde",
              sde(V, (sub(al, mul(be, V)), t), (mul(sv, sqrt(V)), sym("Z_v"))), src()),
            F("bates1996.correlation", "Brownian correlation", "correlation",
              eq(mul(d(sym("Z")), d(sym("Z_v"))), mul(rho, d(t))), src()),
            F("bates1996.jump_size", "Lognormal jump sizes", "distribution",
              distributed(log(add(1, k)), "Normal", sub(log(add(1, kb)), div(pow_(de, 2), 2)),
                          pow_(de, 2)), src()),
            F("bates1996.jump_arrival", "Poisson jump arrivals", "distribution",
              distributed(d(sym("q")), "Poisson", mul(lam, d(t))), src()),
            F("bates1996.forward", "Forward price", "definition", eq(sym("F"), mul(Sx, exp(mul(b, T)))),
              src()),
            F("bates1996.call", "European call price", "price",
              eq(sym("c"), mul(exp(mul(neg(r), T)),
                               sub(mul(sym("F"), idx("P", 1)), mul(X, idx("P", 2))))), src(**rst)),
            F("bates1996.P_1", "Share-measure exercise probability", "probability",
              eq(idx("P", 1), add(half, mul(div(1, PI), integral(Re(div(
                  mul(exp(mul(neg(I), phi, log(X))), apply("psi", sub(phi, I))),
                  mul(I, phi, sym("F")))), "phi", 0, INF)))), src(**rst)),
            F("bates1996.P_2", "Risk-neutral exercise probability", "probability",
              eq(idx("P", 2), add(half, mul(div(1, PI), integral(Re(div(
                  mul(exp(mul(neg(I), phi, log(X))), apply("psi", phi)), mul(I, phi))),
                  "phi", 0, INF)))), src(**rst)),
            F("bates1996.psi", "Characteristic function of ln S_T", "characteristic_function",
              eq(apply("psi", u), exp(add(
                  mul(iu, add(log(Sx), mul(sub(b, mul(lam, kb)), T))),
                  apply("A", u), mul(apply("B", u), V),
                  mul(lam, T, sub(mul(pow_(add(1, kb), iu),
                                      exp(mul(div(pow_(de, 2), 2), iu, sub(iu, 1)))), 1))))),
              src(**rst)),
            F("bates1996.A", "Variance contribution A(u)", "definition",
              eq(apply("A", u), mul(div(al, pow_(sv, 2)), sub(mul(sub(core, dd), T), mul(
                  2, log(div(sub(1, mul(gg, edT)), sub(1, gg))))))), src(**rst)),
            F("bates1996.B", "Variance loading B(u)", "definition",
              eq(apply("B", u), mul(div(sub(core, dd), pow_(sv, 2)),
                                    div(sub(1, edT), sub(1, mul(gg, edT))))), src(**rst)),
            F("bates1996.d", "d(u)", "definition",
              eq(dd, sqrt(add(pow_(core, 2), mul(pow_(sv, 2), add(iu, pow_(u, 2)))))), src(**rst)),
            F("bates1996.g", "g(u)", "definition", eq(gg, div(sub(core, dd), add(core, dd))),
              src(**rst)),
        ],
        "checks": [
            {"id": "martingale", "kind": "compare",
             "description": "psi(-i) = E[S_T] = S e^{bT} (jump compensator is right)",
             "target_ast": Re(apply("psi", neg(I))), "against_ast": mul(Sx, exp(mul(b, T))),
             "inputs": {"S": 1.6, "V": 0.01, "T": 0.5, "b": -0.02, "lambdastar": 0.6,
                        "kbarstar": -0.04, "alpha": 0.02, "betastar": 1.4, "sigma_v": 0.3,
                        "rho": 0.1, "delta": 0.08}, "rel_tol": 1e-12},
            {"id": "no-jump-limit-is-heston", "kind": "compare",
             "description": "lambda* = 0 reproduces Heston's original eq. (10)",
             "target": "bates1996.call", "against": "heston1993.call",
             "inputs": {"S": 100.0, "V": 0.04, "T": 0.75, "b": 0.03, "r": 0.03, "X": 95.0,
                        "lambdastar": 0.0, "kbarstar": 0.0, "delta": 0.1, "alpha": 0.075,
                        "betastar": 1.5, "sigma_v": 0.5, "rho": -0.6,
                        "v": 0.04, "tau": 0.75, "K": 95.0, "kappa": 1.5, "theta": 0.05,
                        "sigma": 0.5, "lambda": 0.0}, "rel_tol": 1e-8},
            {"id": "monte-carlo", "kind": "monte_carlo",
             "description": "Euler simulation with Poisson jumps reproduces the Fourier price",
             "sde": ["bates1996.spot_sde", "bates1996.variance_sde"],
             "correlation": ["bates1996.correlation"], "jumps": ["bates1996.jump_size"],
             "time": "t", "horizon": "T",
             "payoff_ast": mul(exp(mul(neg(r), T)), mx(sub(Sx, X), 0)),
             "against": "bates1996.call",
             "inputs": {"S": 100.0, "V": 0.03, "T": 0.5, "b": 0.01, "r": 0.01, "X": 100.0,
                        "lambdastar": 1.0, "kbarstar": -0.05, "delta": 0.1, "alpha": 0.06,
                        "betastar": 2.0, "sigma_v": 0.4, "rho": -0.5},
             "paths": 200000, "steps": 250, "seed": 4, "abs_tol": 0.03},
        ],
    }


# ---------------------------------------------------------------------------
# SABR: Hagan, Kumar, Lesniewski & Woodward 2002
# ---------------------------------------------------------------------------

def sabr():
    f, K, al, be, nu, rho, tex = (sym(x) for x in ("f", "K", "alpha", "beta", "nu", "rho", "t_ex"))
    z = sym("z")
    omb = sub(1, be)
    fk = mul(f, K)
    lfk = log(div(f, K))
    return {
        "paper": {"id": "hagan2002", "short": "SABR 2002", "transcription_status": "core-complete"},
        "symbols": [
            S("Fhat", "state", "Forward under its forward measure", domain="nonnegative"),
            S("alphahat", "state", "Stochastic volatility", domain="positive"),
            S("t", "time", "Calendar time"),
            S("W_1", "brownian_motion", "Brownian motion driving the forward"),
            S("W_2", "brownian_motion", "Brownian motion driving the volatility"),
            S("f", "parameter", "Today's forward"),
            S("K", "parameter", "Strike"),
            S("alpha", "parameter", "Today's volatility level alpha-hat(0)"),
            S("beta", "parameter", "CEV exponent, 0 <= beta <= 1"),
            S("nu", "parameter", "Volatility of volatility"),
            S("rho", "parameter", "Correlation of W_1 and W_2"),
            S("t_ex", "time", "Time to exercise"),
        ],
        "formulas": [
            F("hagan2002.forward_sde", "SABR forward dynamics", "sde",
              sde(sym("Fhat"), (mul(sym("alphahat"), pow_(sym("Fhat"), be)), sym("W_1"))),
              src("(2.13)")),
            F("hagan2002.vol_sde", "SABR volatility dynamics", "sde",
              sde(sym("alphahat"), (mul(nu, sym("alphahat")), sym("W_2"))), src("(2.13)")),
            F("hagan2002.correlation", "Brownian correlation", "correlation",
              eq(mul(d(sym("W_1")), d(sym("W_2"))), mul(rho, d(sym("t")))), src("(2.13)")),
            F("hagan2002.sigma_B", "Hagan lognormal implied volatility", "approximation",
              approx(sym("sigma_B"), mul(
                  div(al, mul(pow_(fk, div(omb, 2)), add(
                      1, mul(div(pow_(omb, 2), 24), pow_(lfk, 2)),
                      mul(div(pow_(omb, 4), 1920), pow_(lfk, 4))))),
                  div(z, apply("x", z)),
                  add(1, mul(add(
                      mul(div(pow_(omb, 2), 24), div(pow_(al, 2), pow_(fk, omb))),
                      div(mul(rho, be, nu, al), mul(4, pow_(fk, div(omb, 2)))),
                      mul(div(sub(2, mul(3, pow_(rho, 2))), 24), pow_(nu, 2))), tex)))),
              src("(2.17a)")),
            F("hagan2002.z", "z", "definition",
              eq(z, mul(div(nu, al), pow_(fk, div(omb, 2)), lfk)), src("(2.17b)")),
            F("hagan2002.x", "x(z)", "definition",
              eq(apply("x", z), log(div(sub(add(sqrt(add(sub(1, mul(2, rho, z)), pow_(z, 2))), z),
                                            rho), sub(1, rho)))), src("(2.17c)")),
            F("hagan2002.sigma_ATM", "At-the-money implied volatility", "approximation",
              approx(sym("sigma_ATM"), mul(div(al, pow_(f, omb)), add(1, mul(add(
                  mul(div(pow_(omb, 2), 24), div(pow_(al, 2), pow_(f, mul(2, omb)))),
                  div(mul(rho, be, al, nu), mul(4, pow_(f, omb))),
                  mul(div(sub(2, mul(3, pow_(rho, 2))), 24), pow_(nu, 2))), tex)))),
              src("(2.18)")),
        ],
        "checks": [
            {"id": "atm-limit", "kind": "compare",
             "description": "(2.17) tends to (2.18) as K -> f",
             "target": "hagan2002.sigma_B", "against": "hagan2002.sigma_ATM",
             "inputs": {"f": 0.03, "K": 0.030000003, "alpha": 0.035, "beta": 0.5, "nu": 0.45,
                        "rho": -0.25, "t_ex": 2.0}, "rel_tol": 1e-6},
            {"id": "lognormal-no-volvol", "kind": "compare",
             "description": "beta = 1, nu -> 0 gives flat Black vol alpha",
             "target": "hagan2002.sigma_B", "expected": 0.2,
             "inputs": {"f": 100.0, "K": 120.0, "alpha": 0.2, "beta": 1.0, "nu": 1e-9,
                        "rho": 0.0, "t_ex": 1.0}, "rel_tol": 1e-8},
            {"id": "monte-carlo", "kind": "monte_carlo",
             "description": "Simulated SABR call vs Black-76 at Hagan's vol (asymptotic, loose tol)",
             "sde": ["hagan2002.forward_sde", "hagan2002.vol_sde"],
             "correlation": ["hagan2002.correlation"], "time": "t", "horizon": "t_ex",
             "payoff_ast": mx(sub(sym("Fhat"), K), 0), "against": "black1976.call",
             "bind": {"s": "hagan2002.sigma_B"},
             "inputs": {"Fhat": 100.0, "alphahat": 0.2, "f": 100.0, "K": 110.0, "alpha": 0.2,
                        "beta": 1.0, "nu": 0.3, "rho": -0.3, "t_ex": 1.0,
                        "F": 100.0, "cstar": 110.0, "t": 1.0, "r": 0.0},
             "paths": 200000, "steps": 250, "seed": 5, "abs_tol": 0.05},
        ],
    }


# ---------------------------------------------------------------------------
# ZABR: Andreasen & Huge 2011 (SSRN), Caspers 2015 implementation note
# ---------------------------------------------------------------------------

def zabr():
    return {
        "paper": {"id": "zabr", "short": "ZABR 2011/2015", "transcription_status": "dynamics-only",
                  "bib": ["andreasen2011", "caspers2015"]},
        "symbols": [
            S("F", "state", "Forward", domain="nonnegative"),
            S("alpha", "state", "Stochastic volatility", domain="positive"),
            S("t", "time", "Calendar time"),
            S("beta", "parameter", "CEV exponent of the forward"),
            S("gamma", "parameter", "CEV exponent of the volatility (gamma = 1 is SABR)"),
            S("nu", "parameter", "Volatility of volatility"),
            S("rho", "parameter", "Correlation"),
            S("W", "brownian_motion", "Brownian motion driving the forward"),
            S("Z", "brownian_motion", "Brownian motion driving the volatility"),
        ],
        "formulas": [
            F("zabr.forward_sde", "ZABR forward dynamics", "sde",
              sde(sym("F"), (mul(sym("alpha"), pow_(sym("F"), sym("beta"))), sym("W"))),
              src(fidelity="restated", ref="Caspers (2015) notation")),
            F("zabr.vol_sde", "ZABR volatility dynamics: CEV power gamma on the volatility", "sde",
              sde(sym("alpha"), (mul(sym("nu"), pow_(sym("alpha"), sym("gamma"))), sym("Z"))),
              src(fidelity="restated", ref="Caspers (2015) notation")),
            F("zabr.correlation", "Brownian correlation", "correlation",
              eq(mul(d(sym("W")), d(sym("Z"))), mul(sym("rho"), d(sym("t")))),
              src(fidelity="restated")),
        ],
        "checks": [
            {"id": "gamma-one-is-sabr-vol", "kind": "sde_reduction",
             "description": "gamma = 1 reduces the ZABR volatility SDE to SABR (2.13)",
             "target": "zabr.vol_sde", "against": "hagan2002.vol_sde", "subs": {"gamma": 1},
             "rename": {"alpha": "alphahat", "Z": "W_2"}},
            {"id": "forward-is-sabr-forward", "kind": "sde_reduction",
             "description": "The ZABR forward SDE is the SABR forward SDE",
             "target": "zabr.forward_sde", "against": "hagan2002.forward_sde", "subs": {},
             "rename": {"alpha": "alphahat", "F": "Fhat", "W": "W_1"}},
        ],
    }


# ---------------------------------------------------------------------------
# Sidani 2014: normal (arithmetic) Heston
# ---------------------------------------------------------------------------

def sidani():
    Fw, v, t, T, K = sym("F"), sym("v"), sym("t"), sym("T"), sym("K")
    kap, th, xi, rho, u = sym("kappa"), sym("theta"), sym("xi"), sym("rho"), sym("u")
    core = sub(kap, mul(I, rho, xi, u))
    D, G = apply("D", u), apply("G", u)
    eDT = exp(mul(neg(D), T))
    der = dict(fidelity="derived",
               ref="Derived here from the affine structure of the model; compare with Sidani's "
                   "closed form once the PDF is in hand")
    return {
        "paper": {"id": "sidani2014", "short": "Sidani 2014", "transcription_status": "derived-pending-pdf"},
        "symbols": [
            S("F", "state", "Forward price (normal dynamics)"),
            S("v", "state", "Instantaneous variance", domain="nonnegative"),
            S("t", "time", "Calendar time"),
            S("T", "time", "Time to expiry"),
            S("K", "parameter", "Strike"),
            S("kappa", "parameter", "Mean-reversion speed"),
            S("theta", "parameter", "Long-run variance"),
            S("xi", "parameter", "Volatility of variance"),
            S("rho", "parameter", "Correlation"),
            S("W", "brownian_motion", "Brownian motion driving F"),
            S("Z", "brownian_motion", "Brownian motion driving v"),
            S("u", "integration_variable", "Fourier variable"),
        ],
        "formulas": [
            F("sidani2014.forward_sde", "Normal forward dynamics: Heston with sqrt(v) not sqrt(v) S",
              "sde", sde(Fw, (sqrt(v), sym("W"))), src(fidelity="restated"),
              notes="The only difference from Heston's eq. (1) is the missing factor S."),
            F("sidani2014.variance_sde", "Variance dynamics (as Heston)", "sde",
              sde(v, (mul(kap, sub(th, v)), t), (mul(xi, sqrt(v)), sym("Z"))),
              src(fidelity="restated")),
            F("sidani2014.correlation", "Brownian correlation", "correlation",
              eq(mul(d(sym("W")), d(sym("Z"))), mul(rho, d(t))), src(fidelity="restated")),
            F("sidani2014.cf", "Characteristic function of F_T - F", "characteristic_function",
              eq(apply("phi", u), exp(add(apply("A", u), mul(apply("B", u), v)))), src(**der)),
            F("sidani2014.A", "A(u)", "definition",
              eq(apply("A", u), mul(kap, th, sub(
                  neg(div(mul(pow_(u, 2), T), add(core, D))),
                  mul(div(2, pow_(xi, 2)), log(div(sub(1, mul(G, eDT)), sub(1, G))))))),
              src(**der),
              notes="Uses core - D = -xi^2 u^2 / (core + D) to avoid cancellation as xi -> 0."),
            F("sidani2014.B", "B(u)", "definition",
              eq(apply("B", u), neg(div(mul(pow_(u, 2), sub(1, eDT)),
                                        mul(add(core, D), sub(1, mul(G, eDT)))))), src(**der)),
            F("sidani2014.D", "D(u)", "definition",
              eq(D, sqrt(add(pow_(core, 2), mul(pow_(xi, 2), pow_(u, 2))))), src(**der),
              notes="Heston's d with u^2 in place of u^2 + iu: no convexity term for normal dynamics."),
            F("sidani2014.G", "G(u)", "definition",
              eq(G, neg(div(mul(pow_(xi, 2), pow_(u, 2)), pow_(add(core, D), 2)))), src(**der),
              notes="(core - D)/(core + D), rationalised."),
            F("sidani2014.call", "Undiscounted call price", "price",
              eq(sym("C"), add(div(sub(Fw, K), 2), mul(div(1, PI), integral(
                  div(sub(1, Re(mul(exp(mul(I, u, sub(Fw, K))), apply("phi", u)))), pow_(u, 2)),
                  "u", 0, INF)))), src(**der),
              notes="From E[Y^+] = E[Y]/2 + E|Y|/2 and E|Y| = (2/pi) int_0^inf (1 - Re phi_Y(u))/u^2 du."),
        ],
        "checks": [
            {"id": "bachelier-limit", "kind": "compare",
             "description": "xi -> 0 with v = theta recovers the Bachelier price",
             "target": "sidani2014.call", "against": "bachelier1900.call",
             "bind": {"sigma": sqrt(th)},
             "inputs": {"F": 100.0, "K": 104.0, "v": 64.0, "T": 1.0, "kappa": 1.0, "theta": 64.0,
                        "xi": 0.01, "rho": 0.0}, "rel_tol": 1e-5},
            {"id": "monte-carlo", "kind": "monte_carlo",
             "description": "Euler simulation of the normal-SV SDEs reproduces the Fourier price",
             "sde": ["sidani2014.forward_sde", "sidani2014.variance_sde"],
             "correlation": ["sidani2014.correlation"], "time": "t", "horizon": "T",
             "payoff_ast": mx(sub(Fw, K), 0), "against": "sidani2014.call",
             "inputs": {"F": 100.0, "K": 105.0, "v": 64.0, "T": 1.0, "kappa": 1.5,
                        "theta": 81.0, "xi": 6.0, "rho": -0.5},
             "paths": 200000, "steps": 250, "seed": 6, "abs_tol": 0.03},
        ],
    }


# ---------------------------------------------------------------------------
# Alos, Bures & Vives 2026: jump-diffusion stochastic-volatility Bachelier
# ---------------------------------------------------------------------------

def alos():
    X, t, T = sym("X"), sym("t"), sym("T")
    rst = dict(fidelity="restated", ref="Model class as described in the abstract; notation ours")
    return {
        "paper": {"id": "alos2026", "short": "Alòs, Burés & Vives 2026",
                  "transcription_status": "dynamics-only"},
        "symbols": [
            S("X", "state", "Asset price (arithmetic dynamics, martingale)"),
            S("sigma", "process", "Adapted stochastic volatility process"),
            S("W", "brownian_motion", "Brownian motion driving X, W = rho B + sqrt(1-rho^2) B'"),
            S("Z", "levy_process", "Pure-jump Levy process with drift making X a martingale"),
            S("t", "time", "Calendar time"),
            S("T", "time", "Expiry"),
            S("N_t", "process", "Poisson counter of the compound-Poisson case"),
            S("Y", "random_variable", "i.i.d. jump sizes (indexed Y_i)"),
            S("i", "index", "Jump index"),
            S("lambda", "parameter", "Jump intensity"),
            S("K", "parameter", "Strike"),
            S("I", "variable", "Bachelier implied volatility"),
        ],
        "formulas": [
            F("alos2026.price_sde", "Jump-diffusion SV Bachelier dynamics", "sde",
              sde(X, (sym("sigma"), sym("W")), (1, sym("Z"))), src(**rst)),
            F("alos2026.compound_poisson", "Compensated compound-Poisson jump part", "definition",
              eq(sym("Z"), sub({"op": "Sum", "body": idx("Y", sym("i")), "var": sym("i"),
                                "lower": num(1), "upper": sym("N_t")},
                               mul(sym("lambda"), t, expect(sym("Y"))))), src(**rst)),
            F("alos2026.atm_iv", "ATM Bachelier implied volatility (defining relation)",
              "definition",
              eq(expect(call("max", sub({"op": "Symbol", "name": "X_T"}, sym("X_0")), 0)),
                 div(mul(sym("I"), sqrt(T)), sqrt(mul(2, PI)))),
              src(fidelity="restated"),
              notes="Bachelier ATM price is I sqrt(T) / sqrt(2 pi); the theorems give the "
                    "T -> 0 level and skew of I."),
        ],
        "checks": [],
        "extra_symbols": [S("X_T", "variable", "Terminal price"), S("X_0", "parameter", "Spot")],
    }


PAPERS = [bachelier, black, heston, bates, sabr, zabr, sidani, alos]


def main():
    bib = __import__("tomllib").load(open(os.path.join(ROOT, "bibliography.toml"), "rb"))
    meta = {p["id"]: p for p in bib["papers"]}
    for build in PAPERS:
        p = build()
        pid = p["paper"]["id"]
        refs = p["paper"].pop("bib", [pid])
        p["paper"] = {**p["paper"], "title": meta[refs[0]]["title"], "bibliography": refs}
        p["symbols"] += p.pop("extra_symbols", [])
        p["formulas"] = p.pop("extra_formulas", []) + p["formulas"]
        path = os.path.join(ROOT, "papers", f"{pid}.toml")
        with open(path, "w") as fh:
            fh.write(emit(p))
        print("wrote", os.path.relpath(path, ROOT))


if __name__ == "__main__":
    main()
