"""Authoring source for the formulas.toml files in the as-of tree (see research/tools/asof.py).

Formulas are written with the small DSL in ``mathast`` and emitted as TOML with
the Math AST embedded as JSON. The TOML files are the library; this script only
makes writing deep ASTs by hand less error-prone. Re-run after editing:

    python research/tools/author_papers.py && python research/tools/validate.py
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

from mathast import (  # noqa: E402
    I, INF, PI, add, apply, approx, call, const, d, def_key, distributed, div, eq, exp,
    expect, idx, integral, latex, log, mul, neg, num, pow_, sde, sqrt, sub, sym, to_json,
)

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
N = lambda x: call("N", x)  # noqa: E731
n = lambda x: call("n", x)  # noqa: E731
Re = lambda x: call("Re", x)  # noqa: E731
mx = lambda a, b: call("max", a, b)  # noqa: E731
half = div(1, 2)


# ---------------------------------------------------------------------------
# TOML emission
# ---------------------------------------------------------------------------

def q(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def val(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return q(v)
    if isinstance(v, list):
        return "[" + ", ".join(val(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{ " + ", ".join(f"{k} = {val(x)}" for k, x in v.items()) + " }"
    raise TypeError(v)


def ml(s: str) -> str:
    assert "'''" not in s
    return "'''\n" + s + "\n'''"


def emit(paper: dict) -> str:
    out = ["# Generated by research/tools/author_papers.py -- Math AST library entry.",
           "# ast fields hold canonical Math AST as JSON (see research/schema/math_ast.md).",
           "schema_version = 1", "", "[paper]"]
    for k, v in paper["paper"].items():
        out.append(f"{k} = {val(v)}")
    for s in paper["symbols"]:
        out += ["", "[[symbols]]"] + [f"{k} = {val(v)}" for k, v in s.items()]
    defs = {def_key(f["ast"]["args"][0]) for f in paper["formulas"]
            if f["ast"]["op"] in ("Eq", "Approx") and f.get("defines", True)}
    for f in paper["formulas"]:
        ast = f.pop("ast")
        from mathast import free_symbols
        is_def = ast["op"] in ("Eq", "Approx") and f.get("defines", True)
        own = def_key(ast["args"][0]) if is_def else None
        used = free_symbols(ast["args"][1] if is_def else ast)
        deps = sorted(k for k in defs if k and k != own and k.split("[")[0].split("(")[0] in used)
        out += ["", "[[formulas]]"]
        for k, v in f.items():
            out.append(f"{k} = {val(v)}")
        if deps:
            out.append(f"depends_on = {val(deps)}")
        out.append(f"latex = {ml(latex(ast))}")
        out.append(f"ast = {ml(to_json(ast))}")
    for c in paper.get("checks", []):
        out += ["", "[[checks]]"]
        for k, v in c.items():
            if k.endswith("_ast"):
                out.append(f"{k} = {ml(to_json(v))}")
            elif k in ("bind", "oracle_args"):
                out.append(f"{k} = {{ " + ", ".join(
                    f"{b} = {ml(to_json(x)) if isinstance(x, dict) else q(x)}"
                    for b, x in v.items()) + " }")
            else:
                out.append(f"{k} = {val(v)}")
    return "\n".join(out) + "\n"


def S(name, kind, desc, **kw):
    return {"name": name, "kind": kind, "description": desc, **kw}


def F(id_, name, kind, ast, source, **kw):
    return {"id": id_, "name": name, "kind": kind, "source": source, **kw, "ast": ast}


def src(equation=None, page=None, fidelity="verbatim-notation", verified=False, ref=None):
    s = {}
    if ref:
        s["reference"] = ref
    if equation:
        s["equation"] = equation
    if page:
        s["page"] = page
    s["fidelity"] = fidelity
    s["verified_against_pdf"] = verified
    return s


# ---------------------------------------------------------------------------
# Bachelier 1900
# ---------------------------------------------------------------------------

def bachelier():
    x, t, k = sym("x"), sym("t"), sym("k")
    Fw, K, sg, T = sym("F"), sym("K"), sym("sigma"), sym("T")
    dd = sym("d")
    return {
        "paper": {"id": "bachelier1900", "short": "Bachelier 1900",
                  "transcription_status": "core-complete"},
        "symbols": [
            S("x", "variable", "Deviation of the price from its current (true) value"),
            S("t", "time", "Elapsed time"),
            S("k", "parameter", "Bachelier's 'coefficient of instability' (volatility scale)",
              domain="positive"),
            S("F", "variable", "Forward / current price (modern restatement)"),
            S("K", "parameter", "Strike"),
            S("sigma", "parameter", "Normal (absolute) volatility; sigma = k*sqrt(2*pi)",
              domain="positive"),
            S("T", "time", "Time to expiry"),
            S("z", "integration_variable", "Standard normal integration variable"),
        ],
        "formulas": [
            F("bachelier1900.density", "Probability density of the price deviation",
              "density",
              eq(apply("p", x, t), mul(div(1, mul(2, PI, k, sqrt(t))),
                                        exp(neg(div(pow_(x, 2), mul(4, PI, pow_(k, 2), t)))))),
              src(page=38, verified=True),
              notes="'L'expression definitive de la probabilite'. Gaussian with variance "
                    "2 pi k^2 t: the first mathematical Brownian motion."),
            F("bachelier1900.positive_expectation", "Positive mathematical expectation",
              "identity", eq(integral(mul(apply("p", x, t), x), "x", 0, INF), mul(k, sqrt(t))),
              src(page=38, verified=True), defines=False,
              notes="'est proportionnelle a la racine carree du temps'."),
            F("bachelier1900.simple_option_value", "Value of the simple (at-the-money) option",
              "price", eq(sym("a"), mul(k, sqrt(t))),
              src(page=53, verified=True),
              notes="Coefficient d'instabilite: 'a = k sqrt(t)', a being the value (importance) "
                    "of the simple option (prime simple)."),
            F("bachelier1900.call", "Normal-model call price (modern restatement)", "price",
              eq(sym("C"), add(mul(sub(Fw, K), N(dd)), mul(sg, sqrt(T), n(dd)))),
              src(fidelity="modern-restatement",
                  ref="Schachermayer & Teichmann (2008), Math. Finance 18(1)")),
            F("bachelier1900.put", "Normal-model put price (modern restatement)", "price",
              eq(sym("P"), add(mul(sub(K, Fw), N(neg(dd))), mul(sg, sqrt(T), n(dd)))),
              src(fidelity="modern-restatement")),
            F("bachelier1900.d", "Normalised moneyness", "definition",
              eq(dd, div(sub(Fw, K), mul(sg, sqrt(T)))), src(fidelity="modern-restatement")),
        ],
        "checks": [
            {"id": "density-normalised", "kind": "value",
             "description": "Bachelier's density integrates to one",
             "target_ast": integral(apply("p", sym("x"), t), "x", neg(INF), INF),
             "inputs": {"k": 0.8, "t": 2.0}, "expected": 1.0, "rel_tol": 1e-9},
            {"id": "simple-option-from-density", "kind": "compare",
             "description": "a = k sqrt(t) equals the positive expectation of x under p",
             "target_ast": integral(mul(x, apply("p", x, t)), "x", 0, INF),
             "against": "bachelier1900.simple_option_value",
             "inputs": {"k": 0.8, "t": 2.0}, "rel_tol": 1e-8},
            {"id": "call-vs-payoff-integral", "kind": "compare",
             "description": "Closed form equals E[(F + sigma sqrt(T) Z - K)^+]",
             "target": "bachelier1900.call",
             "against_ast": integral(mul(mx(sub(add(Fw, mul(sg, sqrt(T), sym("z"))), K), 0),
                                         n(sym("z"))), "z", neg(INF), INF),
             "inputs": {"F": 100.0, "K": 103.0, "sigma": 12.0, "T": 0.75}, "rel_tol": 1e-7},
            {"id": "put-call-parity", "kind": "compare", "description": "C - P = F - K",
             "target_ast": sub(sym("C"), sym("P")), "against_ast": sub(Fw, K),
             "inputs": {"F": 100.0, "K": 91.0, "sigma": 9.0, "T": 1.5}, "rel_tol": 1e-12},
            {"id": "modern-vs-1900-atm", "kind": "compare",
             "description": "Modern ATM call with sigma = k sqrt(2 pi) equals Bachelier's a = k sqrt(t)",
             "target": "bachelier1900.call", "against": "bachelier1900.simple_option_value",
             "bind": {"sigma": mul(k, sqrt(mul(2, PI)))},
             "inputs": {"F": 100.0, "K": 100.0, "k": 3.0, "T": 0.5, "t": 0.5}, "rel_tol": 1e-12},
            {"id": "monte-carlo", "kind": "monte_carlo",
             "description": "Euler simulation of dF = sigma dW reproduces the call price",
             "sde": ["bachelier1900.sde"], "time": "t", "horizon": "T",
             "payoff_ast": mx(sub(Fw, K), 0), "against": "bachelier1900.call",
             "inputs": {"F": 100.0, "K": 104.0, "sigma": 10.0, "T": 1.0},
             "paths": 200000, "steps": 20, "seed": 1, "abs_tol": 0.0},
        ],
        "extra_formulas": [
            F("bachelier1900.sde", "Arithmetic Brownian motion (modern restatement)", "sde",
              sde(Fw, (sg, sym("W"))), src(fidelity="modern-restatement")),
        ],
        "extra_symbols": [S("W", "brownian_motion", "Standard Brownian motion")],
    }


# ---------------------------------------------------------------------------
# Black 1976
# ---------------------------------------------------------------------------

def black():
    Fw, c_, s, t, r = sym("F"), sym("cstar"), sym("s"), sym("t"), sym("r")
    d1, d2 = sym("d_1"), sym("d_2")
    return {
        "paper": {"id": "black1976", "short": "Black 1976", "transcription_status": "core-complete"},
        "symbols": [
            S("F", "state", "Futures price", domain="positive"),
            S("cstar", "parameter", "Exercise price (Black writes c*)"),
            S("s", "parameter", "Volatility: s^2 is the variance rate of dF/F", domain="positive"),
            S("t", "time", "Time to maturity"),
            S("r", "parameter", "Continuously compounded interest rate"),
            S("z", "brownian_motion", "Standard Brownian motion"),
            S("tau", "time", "Calendar time along simulated paths"),
            S("T", "time", "Horizon used by the Monte Carlo check"),
            S("y", "integration_variable", "Standard normal integration variable"),
        ],
        "formulas": [
            F("black1976.sde", "Lognormal futures dynamics (restated)", "sde",
              sde(Fw, (mul(s, Fw), sym("z"))), src(fidelity="restated"),
              notes="Driftless under the pricing measure; time variable tau."),
            F("black1976.call", "Call on a futures contract", "price",
              eq(sym("c"), mul(exp(mul(neg(r), t)), sub(mul(Fw, N(d1)), mul(c_, N(d2))))),
              src()),
            F("black1976.d_1", "d1", "definition",
              eq(d1, div(add(log(div(Fw, c_)), mul(div(pow_(s, 2), 2), t)), mul(s, sqrt(t)))),
              src()),
            F("black1976.d_2", "d2", "definition", eq(d2, sub(d1, mul(s, sqrt(t)))), src()),
            F("black1976.intrinsic", "Intrinsic value: the call's s -> 0 limit", "price",
              eq(sym("c_0"), mul(exp(mul(neg(r), t)), mx(sub(Fw, c_), 0))),
              src(fidelity="derived"),
              notes="lim_{s -> 0} of the call; QuantLib's blackFormula returns this when "
                    "stdDev = 0."),
            F("black1976.put", "Put on a futures contract (via parity)", "price",
              eq(sym("p"), mul(exp(mul(neg(r), t)),
                               sub(mul(c_, N(neg(d2))), mul(Fw, N(neg(d1)))))),
              src(fidelity="derived")),
        ],
        "checks": [
            {"id": "put-call-parity", "kind": "compare", "description": "c - p = e^{-rt}(F - c*)",
             "target_ast": sub(sym("c"), sym("p")),
             "against_ast": mul(exp(mul(neg(r), t)), sub(Fw, c_)),
             "inputs": {"F": 100.0, "cstar": 95.0, "s": 0.25, "t": 0.8, "r": 0.03},
             "rel_tol": 1e-12},
            {"id": "call-vs-lognormal-integral", "kind": "compare",
             "description": "Closed form equals discounted E[(F_T - c*)^+] under the lognormal law",
             "target": "black1976.call",
             "against_ast": mul(exp(mul(neg(r), t)), integral(
                 mul(mx(sub(mul(Fw, exp(add(neg(mul(div(pow_(s, 2), 2), t)),
                                            mul(s, sqrt(t), sym("y"))))), c_), 0), n(sym("y"))),
                 "y", neg(INF), INF)),
             "inputs": {"F": 100.0, "cstar": 110.0, "s": 0.3, "t": 1.25, "r": 0.02},
             "rel_tol": 1e-7},
            {"id": "monte-carlo", "kind": "monte_carlo",
             "description": "Euler simulation of dF = s F dz reproduces the call price",
             "sde": ["black1976.sde"], "time": "tau", "horizon": "t",
             "payoff_ast": mul(exp(mul(neg(r), t)), mx(sub(Fw, c_), 0)),
             "against": "black1976.call",
             "inputs": {"F": 100.0, "cstar": 105.0, "s": 0.2, "t": 1.0, "r": 0.01},
             "paths": 200000, "steps": 200, "seed": 2, "abs_tol": 0.02},
        ],
    }


# ---------------------------------------------------------------------------
# Heston 1993
# ---------------------------------------------------------------------------

def heston():
    Sx, v, t = sym("S"), sym("v"), sym("t")
    mu, kap, th, sg, rho, lam = (sym(x) for x in ("mu", "kappa", "theta", "sigma", "rho", "lambda"))
    K, r, tau, phi, j, x = sym("K"), sym("r"), sym("tau"), sym("phi"), sym("j"), sym("x")
    a = sym("a")
    bj, uj, dj, gj = idx("b", j), idx("u", j), idx("d", j), idx("g", j)
    rsp = mul(rho, sg, phi, I)  # rho sigma phi i

    def trap(name_c, name_d, name_g, name_f, sign):
        """Heston's original form (sign=+1) or Albrecher et al. 'little trap' form (sign=-1)."""
        dd = dj if sign > 0 else neg(dj)
        core = add(sub(bj, rsp), dd)                     # b_j - rho sigma phi i +/- d_j
        other = sub(sub(bj, rsp), dd)
        g = idx(name_g, j)
        edt = exp(mul(dd, tau))
        return [
            eq(idx(name_c, j), add(mul(r, phi, I, tau), mul(div(a, pow_(sg, 2)), sub(
                mul(core, tau), mul(2, log(div(sub(1, mul(g, edt)), sub(1, g)))))))),
            eq(idx(name_d, j), mul(div(core, pow_(sg, 2)),
                                   div(sub(1, edt), sub(1, mul(g, edt))))),
            eq(g, div(core, other)),
            eq(idx(name_f, j), exp(add(idx(name_c, j), mul(idx(name_d, j), v), mul(I, phi, x)))),
        ]

    orig = trap("C", "D", "g", "f", +1)
    alt = trap("Ct", "Dt", "gt", "ft", -1)
    h = src
    alb = dict(fidelity="restated", ref="Albrecher, Mayer, Schoutens & Tistaert (2007), "
                                        "'The Little Heston Trap', Wilmott Magazine, Jan 2007")
    return {
        "paper": {"id": "heston1993", "short": "Heston 1993", "transcription_status": "core-complete",
                  "bib": ["heston1993", "albrecher2007"]},
        "symbols": [
            S("S", "state", "Spot asset price", domain="positive"),
            S("v", "state", "Instantaneous variance", domain="nonnegative"),
            S("t", "time", "Calendar time"),
            S("mu", "parameter", "Spot drift (set mu = r for risk-neutral simulation)"),
            S("kappa", "parameter", "Mean-reversion speed of variance"),
            S("theta", "parameter", "Long-run variance"),
            S("sigma", "parameter", "Volatility of volatility"),
            S("rho", "parameter", "Correlation between z_1 and z_2"),
            S("lambda", "parameter", "Price of volatility risk"),
            S("z_1", "brownian_motion", "Brownian motion driving the spot"),
            S("z_2", "brownian_motion", "Brownian motion driving the variance"),
            S("K", "parameter", "Strike"),
            S("r", "parameter", "Risk-free rate (constant)"),
            S("tau", "time", "Time to maturity, T - t"),
            S("phi", "integration_variable", "Fourier variable"),
            S("j", "index", "Probability index, j in {1, 2}"),
        ],
        "formulas": [
            F("heston1993.spot_sde", "Spot dynamics", "sde",
              sde(Sx, (mul(mu, Sx), t), (mul(sqrt(v), Sx), sym("z_1"))), h("(1)", 328, verified=True)),
            F("heston1993.variance_sde", "Variance dynamics (square-root process)", "sde",
              sde(v, (mul(kap, sub(th, v)), t), (mul(sg, sqrt(v)), sym("z_2"))), h("(4)", 329, verified=True)),
            F("heston1993.correlation", "Brownian correlation", "correlation",
              eq(mul(d(sym("z_1")), d(sym("z_2"))), mul(rho, d(t))),
              h(page=329, fidelity="restated", verified=True),
              notes="Stated in words after (4): z_2(t) has correlation rho with z_1(t)."),
            F("heston1993.call", "European call price", "price",
              eq(sym("C"), sub(mul(Sx, idx("P", 1)), mul(K, sym("P_tT"), idx("P", 2)))), h("(10)", 330, verified=True)),
            F("heston1993.bond", "Discount bond price (constant rate)", "definition",
              eq(sym("P_tT"), exp(mul(neg(r), tau))), h("(5)", 329, verified=True),
              notes="Heston writes P(t, t + tau) = e^{-r tau}; P_tT is P(t, T) in (10)."),
            F("heston1993.x", "Log spot", "definition", eq(x, log(Sx)), h("(11)", 330, verified=True)),
            F("heston1993.P_j", "In-the-money probabilities", "probability",
              eq(idx("P", j), add(half, mul(div(1, PI), integral(
                  Re(div(mul(exp(mul(neg(I), phi, log(K))), idx("f", j)), mul(I, phi))),
                  "phi", 0, INF)))), h("(18)", 331, verified=True)),
            F("heston1993.f_j", "Characteristic functions", "characteristic_function",
              orig[3], h("(17)", 331, verified=True)),
            F("heston1993.C_j", "C(tau; phi)", "definition", orig[0], h("(17)", 331, verified=True),
              notes="Unnumbered display following (17)."),
            F("heston1993.D_j", "D(tau; phi)", "definition", orig[1], h("(17)", 331, verified=True),
              notes="Unnumbered display following (17)."),
            F("heston1993.g_j", "g", "definition", orig[2], h("(17)", 331, verified=True),
              notes="Unnumbered display following (17)."),
            F("heston1993.d_j", "d", "definition",
              eq(dj, sqrt(sub(pow_(sub(rsp, bj), 2),
                              mul(pow_(sg, 2), sub(mul(2, uj, phi, I), pow_(phi, 2)))))),
              h("(17)", 331, verified=True), notes="Unnumbered display following (17)."),
            F("heston1993.u_1", "u_1", "definition", eq(idx("u", 1), half), h("(12)", 330, verified=True)),
            F("heston1993.u_2", "u_2", "definition", eq(idx("u", 2), neg(half)), h("(12)", 330, verified=True)),
            F("heston1993.a", "a", "definition", eq(a, mul(kap, th)), h("(12)", 330, verified=True)),
            F("heston1993.b_1", "b_1", "definition", eq(idx("b", 1), sub(add(kap, lam), mul(rho, sg))),
              h("(12)", 330, verified=True)),
            F("heston1993.b_2", "b_2", "definition", eq(idx("b", 2), add(kap, lam)), h("(12)", 330, verified=True)),
            F("heston1993.ft_j", "Characteristic functions, rotation-count-safe form",
              "characteristic_function", alt[3], h(**alb),
              notes="Algebraically equal to (17); continuous in phi for long maturities."),
            F("heston1993.Ct_j", "C(tau; phi), little-trap form", "definition", alt[0], h(**alb)),
            F("heston1993.Dt_j", "D(tau; phi), little-trap form", "definition", alt[1], h(**alb)),
            F("heston1993.gt_j", "g, little-trap form", "definition", alt[2], h(**alb)),
            F("heston1993.Pt_j", "In-the-money probabilities, little-trap form", "probability",
              eq(idx("Pt", j), add(half, mul(div(1, PI), integral(
                  Re(div(mul(exp(mul(neg(I), phi, log(K))), idx("ft", j)), mul(I, phi))),
                  "phi", 0, INF)))), h(**alb)),
            F("heston1993.call_trap", "European call price, branch-safe", "price",
              eq(sym("C_trap"), sub(mul(Sx, idx("Pt", 1)), mul(K, sym("P_tT"), idx("Pt", 2)))),
              h(**alb),
              notes="Eq. (10) with (17) replaced by the little-trap form. Use this for pricing: "
                    "(17) as printed takes a principal-branch complex log whose argument can cross "
                    "the branch cut (e.g. kappa=1.5, sigma=0.3, rho=-0.7, tau=2), which moves the "
                    "price by up to 0.8% (see the quantlib checks)."),
        ],
        "checks": [
            {"id": f"trap-form-agrees-{part}-{jj}", "kind": "compare",
             "description": f"{part} of f_{jj} equals the little-trap form at a sample phi",
             "target_ast": call(part, idx("f", jj)), "against_ast": call(part, idx("ft", jj)),
             "inputs": {"S": 100.0, "v": 0.04, "kappa": 1.5, "theta": 0.05, "sigma": 0.6,
                        "rho": -0.7, "lambda": 0.0, "K": 100.0, "r": 0.02, "tau": 0.5,
                        "phi": 1.7}, "abs_tol": 1e-12}
            for part in ("Re", "Im") for jj in (1, 2)
        ] + [
            {"id": "black-scholes-limit", "kind": "compare",
             "description": "Vol-of-vol -> 0 with v = theta recovers Black-Scholes (via Black 1976)",
             "target": "heston1993.call", "against": "black1976.call",
             "bind": {"F": mul(Sx, exp(mul(r, tau))), "s": sqrt(th)},
             "inputs": {"S": 100.0, "v": 0.04, "kappa": 2.0, "theta": 0.04, "sigma": 0.01,
                        "rho": 0.0, "lambda": 0.0, "K": 105.0, "r": 0.03, "tau": 1.0,
                        "cstar": 105.0, "t": 1.0}, "rel_tol": 2e-4},
            {"id": "monte-carlo", "kind": "monte_carlo",
             "description": "Euler (full truncation) simulation of the SDEs reproduces eq. (10)",
             "sde": ["heston1993.spot_sde", "heston1993.variance_sde"],
             "correlation": ["heston1993.correlation"], "time": "t", "horizon": "tau",
             "payoff_ast": mul(exp(mul(neg(r), tau)), mx(sub(Sx, K), 0)),
             "against": "heston1993.call",
             "inputs": {"S": 100.0, "v": 0.04, "kappa": 1.5, "theta": 0.05, "sigma": 0.5,
                        "rho": -0.7, "lambda": 0.0, "mu": 0.02, "K": 100.0, "r": 0.02,
                        "tau": 1.0}, "paths": 200000, "steps": 250, "seed": 3, "abs_tol": 0.03},
        ],
    }


# ---------------------------------------------------------------------------
# Bates 1996
# ---------------------------------------------------------------------------

def bates():
    Sx, V, t, T, X = sym("S"), sym("V"), sym("t"), sym("T"), sym("X")
    b, lam, kb, k = sym("b"), sym("lambdastar"), sym("kbarstar"), sym("k")
    al, be, sv, rho, de, r = (sym(x) for x in ("alpha", "betastar", "sigma_v", "rho", "delta", "r"))
    u, phi = sym("u"), sym("phi")
    iu = mul(I, u)
    core = sub(be, mul(rho, sv, iu))
    dd, gg = apply("d", u), apply("g", u)
    edT = exp(mul(neg(dd), T))
    rst = dict(fidelity="restated",
               ref="Bates (1996) model with the Heston CF in the Albrecher et al. (2007) form")
    return {
        "paper": {"id": "bates1996", "short": "Bates 1996", "transcription_status": "core-complete"},
        "symbols": [
            S("S", "state", "Spot exchange rate (DM price)", domain="positive"),
            S("V", "state", "Instantaneous variance", domain="nonnegative"),
            S("t", "time", "Calendar time"),
            S("T", "time", "Time to maturity"),
            S("X", "parameter", "Strike (Bates writes X)"),
            S("b", "parameter", "Cost of carry, r - r* for currencies"),
            S("r", "parameter", "Domestic interest rate"),
            S("lambdastar", "parameter", "Risk-neutral jump intensity"),
            S("kbarstar", "parameter", "Risk-neutral mean relative jump size"),
            S("k", "random_variable", "Random relative jump size"),
            S("q", "poisson_process", "Jump counter", intensity="lambdastar"),
            S("alpha", "parameter", "Variance drift intercept (alpha = kappa theta)"),
            S("betastar", "parameter", "Risk-neutral variance mean-reversion speed"),
            S("sigma_v", "parameter", "Volatility of variance"),
            S("rho", "parameter", "Correlation of Z and Z_v"),
            S("delta", "parameter", "Std. dev. of log jump size", domain="nonnegative"),
            S("Z", "brownian_motion", "Brownian motion driving S"),
            S("Z_v", "brownian_motion", "Brownian motion driving V"),
            S("u", "variable", "Characteristic-function argument"),
            S("phi", "integration_variable", "Fourier variable"),
        ],
        "formulas": [
            F("bates1996.spot_sde", "Risk-neutral spot dynamics (jump-diffusion)", "sde",
              sde(Sx, (mul(sub(b, mul(lam, kb)), Sx), t), (mul(sqrt(V), Sx), sym("Z")),
                  (mul(k, Sx), sym("q"))), src(fidelity="restated"),
              notes="Bates writes dS/S = (b - lambda* kbar*) dt + sqrt(V) dZ + k dq*; "
                    "multiplied through by S here."),
            F("bates1996.variance_sde", "Risk-neutral variance dynamics", "sde",
              sde(V, (sub(al, mul(be, V)), t), (mul(sv, sqrt(V)), sym("Z_v"))), src()),
            F("bates1996.correlation", "Brownian correlation", "correlation",
              eq(mul(d(sym("Z")), d(sym("Z_v"))), mul(rho, d(t))), src()),
            F("bates1996.jump_size", "Lognormal jump sizes", "distribution",
              distributed(log(add(1, k)), "Normal", sub(log(add(1, kb)), div(pow_(de, 2), 2)),
                          pow_(de, 2)), src()),
            F("bates1996.jump_arrival", "Poisson jump arrivals", "distribution",
              distributed(d(sym("q")), "Poisson", mul(lam, d(t))), src()),
            F("bates1996.forward", "Forward price", "definition", eq(sym("F"), mul(Sx, exp(mul(b, T)))),
              src()),
            F("bates1996.call", "European call price", "price",
              eq(sym("c"), mul(exp(mul(neg(r), T)),
                               sub(mul(sym("F"), idx("P", 1)), mul(X, idx("P", 2))))), src(**rst)),
            F("bates1996.P_1", "Share-measure exercise probability", "probability",
              eq(idx("P", 1), add(half, mul(div(1, PI), integral(Re(div(
                  mul(exp(mul(neg(I), phi, log(X))), apply("psi", sub(phi, I))),
                  mul(I, phi, sym("F")))), "phi", 0, INF)))), src(**rst)),
            F("bates1996.P_2", "Risk-neutral exercise probability", "probability",
              eq(idx("P", 2), add(half, mul(div(1, PI), integral(Re(div(
                  mul(exp(mul(neg(I), phi, log(X))), apply("psi", phi)), mul(I, phi))),
                  "phi", 0, INF)))), src(**rst)),
            F("bates1996.psi", "Characteristic function of ln S_T", "characteristic_function",
              eq(apply("psi", u), exp(add(
                  mul(iu, add(log(Sx), mul(sub(b, mul(lam, kb)), T))),
                  apply("A", u), mul(apply("B", u), V),
                  mul(lam, T, sub(mul(pow_(add(1, kb), iu),
                                      exp(mul(div(pow_(de, 2), 2), iu, sub(iu, 1)))), 1))))),
              src(**rst)),
            F("bates1996.A", "Variance contribution A(u)", "definition",
              eq(apply("A", u), mul(div(al, pow_(sv, 2)), sub(mul(sub(core, dd), T), mul(
                  2, log(div(sub(1, mul(gg, edT)), sub(1, gg))))))), src(**rst)),
            F("bates1996.B", "Variance loading B(u)", "definition",
              eq(apply("B", u), mul(div(sub(core, dd), pow_(sv, 2)),
                                    div(sub(1, edT), sub(1, mul(gg, edT))))), src(**rst)),
            F("bates1996.d", "d(u)", "definition",
              eq(dd, sqrt(add(pow_(core, 2), mul(pow_(sv, 2), add(iu, pow_(u, 2)))))), src(**rst)),
            F("bates1996.g", "g(u)", "definition", eq(gg, div(sub(core, dd), add(core, dd))),
              src(**rst)),
        ],
        "checks": [
            {"id": "martingale", "kind": "compare",
             "description": "psi(-i) = E[S_T] = S e^{bT} (jump compensator is right)",
             "target_ast": Re(apply("psi", neg(I))), "against_ast": mul(Sx, exp(mul(b, T))),
             "inputs": {"S": 1.6, "V": 0.01, "T": 0.5, "b": -0.02, "lambdastar": 0.6,
                        "kbarstar": -0.04, "alpha": 0.02, "betastar": 1.4, "sigma_v": 0.3,
                        "rho": 0.1, "delta": 0.08}, "rel_tol": 1e-12},
            {"id": "no-jump-limit-is-heston", "kind": "compare",
             "description": "lambda* = 0 reproduces Heston's original eq. (10)",
             "target": "bates1996.call", "against": "heston1993.call",
             "inputs": {"S": 100.0, "V": 0.04, "T": 0.75, "b": 0.03, "r": 0.03, "X": 95.0,
                        "lambdastar": 0.0, "kbarstar": 0.0, "delta": 0.1, "alpha": 0.075,
                        "betastar": 1.5, "sigma_v": 0.5, "rho": -0.6,
                        "v": 0.04, "tau": 0.75, "K": 95.0, "kappa": 1.5, "theta": 0.05,
                        "sigma": 0.5, "lambda": 0.0}, "rel_tol": 1e-8},
            {"id": "monte-carlo", "kind": "monte_carlo",
             "description": "Euler simulation with Poisson jumps reproduces the Fourier price",
             "sde": ["bates1996.spot_sde", "bates1996.variance_sde"],
             "correlation": ["bates1996.correlation"], "jumps": ["bates1996.jump_size"],
             "time": "t", "horizon": "T",
             "payoff_ast": mul(exp(mul(neg(r), T)), mx(sub(Sx, X), 0)),
             "against": "bates1996.call",
             "inputs": {"S": 100.0, "V": 0.03, "T": 0.5, "b": 0.01, "r": 0.01, "X": 100.0,
                        "lambdastar": 1.0, "kbarstar": -0.05, "delta": 0.1, "alpha": 0.06,
                        "betastar": 2.0, "sigma_v": 0.4, "rho": -0.5},
             "paths": 200000, "steps": 250, "seed": 4, "abs_tol": 0.03},
        ],
    }


# ---------------------------------------------------------------------------
# SABR: Hagan, Kumar, Lesniewski & Woodward 2002
# ---------------------------------------------------------------------------

def sabr():
    f, K, al, be, nu, rho, tex = (sym(x) for x in ("f", "K", "alpha", "beta", "nu", "rho", "t_ex"))
    z = sym("z")
    omb = sub(1, be)
    fk = mul(f, K)
    lfk = log(div(f, K))
    return {
        "paper": {"id": "hagan2002", "short": "SABR 2002", "transcription_status": "core-complete"},
        "symbols": [
            S("Fhat", "state", "Forward under its forward measure", domain="nonnegative"),
            S("alphahat", "state", "Stochastic volatility", domain="positive"),
            S("t", "time", "Calendar time"),
            S("W_1", "brownian_motion", "Brownian motion driving the forward"),
            S("W_2", "brownian_motion", "Brownian motion driving the volatility"),
            S("f", "parameter", "Today's forward"),
            S("K", "parameter", "Strike"),
            S("alpha", "parameter", "Today's volatility level alpha-hat(0)"),
            S("beta", "parameter", "CEV exponent, 0 <= beta <= 1"),
            S("nu", "parameter", "Volatility of volatility"),
            S("rho", "parameter", "Correlation of W_1 and W_2"),
            S("t_ex", "time", "Time to exercise"),
        ],
        "formulas": [
            F("hagan2002.forward_sde", "SABR forward dynamics", "sde",
              sde(sym("Fhat"), (mul(sym("alphahat"), pow_(sym("Fhat"), be)), sym("W_1"))),
              src("(2.13)")),
            F("hagan2002.vol_sde", "SABR volatility dynamics", "sde",
              sde(sym("alphahat"), (mul(nu, sym("alphahat")), sym("W_2"))), src("(2.13)")),
            F("hagan2002.correlation", "Brownian correlation", "correlation",
              eq(mul(d(sym("W_1")), d(sym("W_2"))), mul(rho, d(sym("t")))), src("(2.13)")),
            F("hagan2002.sigma_B", "Hagan lognormal implied volatility", "approximation",
              approx(sym("sigma_B"), mul(
                  div(al, mul(pow_(fk, div(omb, 2)), add(
                      1, mul(div(pow_(omb, 2), 24), pow_(lfk, 2)),
                      mul(div(pow_(omb, 4), 1920), pow_(lfk, 4))))),
                  div(z, apply("x", z)),
                  add(1, mul(add(
                      mul(div(pow_(omb, 2), 24), div(pow_(al, 2), pow_(fk, omb))),
                      div(mul(rho, be, nu, al), mul(4, pow_(fk, div(omb, 2)))),
                      mul(div(sub(2, mul(3, pow_(rho, 2))), 24), pow_(nu, 2))), tex)))),
              src("(2.17a)")),
            F("hagan2002.z", "z", "definition",
              eq(z, mul(div(nu, al), pow_(fk, div(omb, 2)), lfk)), src("(2.17b)")),
            F("hagan2002.x", "x(z)", "definition",
              eq(apply("x", z), log(div(sub(add(sqrt(add(sub(1, mul(2, rho, z)), pow_(z, 2))), z),
                                            rho), sub(1, rho)))), src("(2.17c)")),
            F("hagan2002.sigma_ATM", "At-the-money implied volatility", "approximation",
              approx(sym("sigma_ATM"), mul(div(al, pow_(f, omb)), add(1, mul(add(
                  mul(div(pow_(omb, 2), 24), div(pow_(al, 2), pow_(f, mul(2, omb)))),
                  div(mul(rho, be, al, nu), mul(4, pow_(f, omb))),
                  mul(div(sub(2, mul(3, pow_(rho, 2))), 24), pow_(nu, 2))), tex)))),
              src("(2.18)")),
        ],
        "checks": [
            {"id": "atm-limit", "kind": "compare",
             "description": "(2.17) tends to (2.18) as K -> f",
             "target": "hagan2002.sigma_B", "against": "hagan2002.sigma_ATM",
             "inputs": {"f": 0.03, "K": 0.030000003, "alpha": 0.035, "beta": 0.5, "nu": 0.45,
                        "rho": -0.25, "t_ex": 2.0}, "rel_tol": 1e-6},
            {"id": "lognormal-no-volvol", "kind": "compare",
             "description": "beta = 1, nu -> 0 gives flat Black vol alpha",
             "target": "hagan2002.sigma_B", "expected": 0.2,
             "inputs": {"f": 100.0, "K": 120.0, "alpha": 0.2, "beta": 1.0, "nu": 1e-9,
                        "rho": 0.0, "t_ex": 1.0}, "rel_tol": 1e-8},
            {"id": "monte-carlo", "kind": "monte_carlo",
             "description": "Simulated SABR call vs Black-76 at Hagan's vol (asymptotic, loose tol)",
             "sde": ["hagan2002.forward_sde", "hagan2002.vol_sde"],
             "correlation": ["hagan2002.correlation"], "time": "t", "horizon": "t_ex",
             "payoff_ast": mx(sub(sym("Fhat"), K), 0), "against": "black1976.call",
             "bind": {"s": "hagan2002.sigma_B"},
             "inputs": {"Fhat": 100.0, "alphahat": 0.2, "f": 100.0, "K": 110.0, "alpha": 0.2,
                        "beta": 1.0, "nu": 0.3, "rho": -0.3, "t_ex": 1.0,
                        "F": 100.0, "cstar": 110.0, "t": 1.0, "r": 0.0},
             "paths": 200000, "steps": 250, "seed": 5, "abs_tol": 0.05},
        ],
    }


# ---------------------------------------------------------------------------
# ZABR: Andreasen & Huge 2011 (SSRN), Caspers 2015 implementation note
# ---------------------------------------------------------------------------

def zabr():
    s_, z, k, u, y = sym("s"), sym("z"), sym("k"), sym("u"), sym("y")
    eps, rho, gam, tau, v = sym("epsilon"), sym("rho"), sym("gamma"), sym("tau"), sym("v")
    sig = lambda x_: apply("sigma", x_)  # noqa: E731
    veps = lambda x_: apply("varepsilon", x_)  # noqa: E731
    pd = lambda e, var: {"op": "PartialDerivative", "expr": e, "var": sym(var)}  # noqa: E731
    dd = lambda e, var: {"op": "Derivative", "expr": e, "var": sym(var)}  # noqa: E731
    xg = apply("x", s_, z)
    Jy = lambda a_: apply("J", a_)  # noqa: E731
    fy = apply("f", y)
    inv_sig_int = integral(div(1, sig(u)), "u", k, s_)
    sabr_x = lambda yy: div(log(div(add(sub(Jy(yy), rho), mul(eps, yy)), sub(1, rho))), eps)  # noqa: E731
    P = lambda pg, eqn=None, **kw: src(eqn, pg, verified=True, **kw)  # noqa: E731
    typo = "Transcribed with epsilon where the preliminary version prints alpha (typo)."
    return {
        "paper": {"id": "zabr", "short": "ZABR 2011", "transcription_status": "core-complete",
                  "bib": ["andreasen2011", "caspers2015"],
                  "pdf_version": "SSRN 1980726, Preliminary Version, December 2011"},
        "symbols": [
            S("s", "state", "Forward (underlying) price", domain="nonnegative"),
            S("z", "state", "Stochastic volatility scale", domain="positive"),
            S("k", "parameter", "Strike"),
            S("t", "time", "Calendar time"),
            S("T", "time", "Expiry"),
            S("tau", "time", "Time to expiry, T - t"),
            S("W", "brownian_motion", "Brownian motion driving s"),
            S("Z", "brownian_motion", "Brownian motion driving z"),
            S("rho", "parameter", "Correlation of W and Z"),
            S("epsilon", "parameter", "Volatility of volatility"),
            S("gamma", "parameter", "CEV power of the volatility process (gamma = 1 is SABR)"),
            S("sigma", "function", "Local volatility function sigma(s) (non-parametric)"),
            S("varepsilon", "function", "Volatility-of-volatility function epsilon(z)"),
            S("vartheta", "function", "Equivalent local volatility function"),
            S("v", "variable", "Implied normal (Bachelier) volatility"),
            S("vbar", "variable", "Implied Black (lognormal) volatility"),
            S("x", "function", "Transformed variable x(s, z)"),
            S("f", "function", "ZABR profile x = z^{1-gamma} f(y)"),
            S("y", "variable", "Intermediate variable"),
            S("u", "integration_variable", "Dummy integration variable"),
            S("c", "parameter", "Level of sigma(s) = c s^beta (Figure 1 uses 0.0873)"),
            S("beta", "parameter", "CEV power of sigma(s) (Figure 1 uses 0.7)"),
        ],
        "formulas": [
            F("zabr.spot_sde", "Forward dynamics", "sde", sde(s_, (mul(z, sig(s_)), sym("W"))),
              P(3, "(1)")),
            F("zabr.vol_sde", "Volatility dynamics", "sde", sde(z, (veps(z), sym("Z"))), P(3, "(1)")),
            F("zabr.correlation", "Brownian correlation", "correlation",
              eq(mul(d(sym("W")), d(sym("Z"))), mul(rho, d(sym("t")))),
              P(3, fidelity="restated"), notes="Stated in words after (1)."),
            F("zabr.bachelier", "Normal (Bachelier) option pricing formula", "price",
              eq(apply("g", tau, s_, v), add(
                  mul(sub(s_, k), call("Phi", div(sub(s_, k), mul(v, sqrt(tau))))),
                  mul(v, sqrt(tau), call("varphi", div(sub(s_, k), mul(v, sqrt(tau))))))),
              P(3, "(2)")),
            F("zabr.diffusion_condition", "Diffusion (eikonal) condition", "pde",
              eq(1, add(mul(pow_(z, 2), pow_(sig(s_), 2), pow_(pd(xg, "s"), 2)),
                        mul(pow_(veps(z), 2), pow_(pd(xg, "z"), 2)),
                        mul(2, rho, z, sig(s_), veps(z), pd(xg, "s"), pd(xg, "z")))),
              P(4), defines=False, notes="Boundary condition x(s = k, z) = 0."),
            F("zabr.implied_normal_vol", "Implied normal volatility from x", "identity",
              eq(v, div(sub(s_, k), xg)), P(4), defines=False,
              notes="Error O(tau)."),
            F("zabr.deterministic_x", "Deterministic-volatility solution (epsilon(z) = 0)", "identity",
              eq(sym("x"), inv_sig_int), P(5), defines=False),
            F("zabr.local_vol", "Equivalent local volatility", "identity",
              eq(apply("vartheta", k), neg(pow_(pd(sym("x"), "k"), -1))), P(5, "(5)"),
              defines=False),
            F("zabr.local_vol_sde", "Equivalent 1-D local volatility model", "sde",
              sde(s_, (apply("vartheta", s_), sym("W"))), P(5, "(6)")),
            # SABR case, epsilon(z) = epsilon z
            F("zabr.sabr_y", "SABR case: intermediate variable", "definition",
              eq(sym("y_SABR"), mul(div(1, z), inv_sig_int)), P(6)),
            F("zabr.sabr_J", "SABR case: J(y)", "definition",
              eq(Jy(y), sqrt(sub(add(1, mul(pow_(eps, 2), pow_(y, 2))), mul(2, rho, eps, y)))),
              P(6), notes=typo),
            F("zabr.sabr_x", "SABR case: x (7)", "definition",
              eq(sym("x_SABR"), sabr_x(sym("y_SABR"))), P(6, "(7)"),
              notes="x = int_0^y J(u)^{-1} du = (1/epsilon) ln((J(y) - rho + epsilon y)/(1 - rho))."),
            F("zabr.sabr_v", "SABR case: implied normal volatility (7)", "definition",
              eq(sym("v_SABR"), div(sub(s_, k), sym("x_SABR"))), P(6, "(7)")),
            F("zabr.sabr_vbar", "SABR case: implied Black volatility (7)", "definition",
              eq(sym("vbar_SABR"), div(log(div(s_, k)), sym("x_SABR"))), P(6, "(7)")),
            F("zabr.sabr_local_vol", "SABR case: equivalent local volatility", "identity",
              eq(apply("vartheta", k), mul(Jy(y), z, sig(k))), P(7), defines=False),
            F("zabr.figure1_sigma", "sigma(s) used in Figures 1-3", "definition",
              eq(sig(u), mul(sym("c"), pow_(u, sym("beta")))), P(7, fidelity="restated"),
              notes="Figure 1 caption: sigma(s) = 0.0873 s^0.7, epsilon = 0.47, rho = -0.48, T = 10."),
            # ZABR case, epsilon(z) = epsilon z^gamma
            F("zabr.cev_vol_sde", "ZABR volatility dynamics, epsilon(z) = epsilon z^gamma", "sde",
              sde(z, (mul(eps, pow_(z, gam)), sym("Z"))), P(8, fidelity="restated"),
              notes="(1) with the CEV choice of p. 8 (printed as alpha z^gamma; the ODE uses "
                    "epsilon). gamma = 0, not 0.5, corresponds to Heston."),
            F("zabr.cev_spot_sde", "Forward dynamics with sigma(s) = c s^beta", "sde",
              sde(s_, (mul(z, sym("c"), pow_(s_, sym("beta"))), sym("W"))),
              P(7, fidelity="restated")),
            F("zabr.zabr_y", "ZABR case: intermediate variable", "definition",
              eq(sym("y_ZABR"), mul(pow_(z, sub(gam, 2)), inv_sig_int)), P(8)),
            F("zabr.zabr_x", "ZABR case: x = z^{1-gamma} f(y)", "identity",
              eq(sym("x"), mul(pow_(z, sub(1, gam)), fy)), P(8), defines=False),
            F("zabr.ode", "ZABR ODE for f", "ode",
              eq(1, add(mul(apply("A", y), pow_(dd(fy, "y"), 2)),
                        mul(apply("B", y), dd(fy, "y"), fy), mul(sym("C"), pow_(fy, 2)))),
              P(9), defines=False,
              notes="The printed first line reads '+ C'; the rearranged form F(y, f) below "
                    "requires '+ C f^2', transcribed here. f(0) = 0."),
            F("zabr.A", "A(y)", "definition",
              eq(apply("A", y), add(1, mul(pow_(sub(gam, 2), 2), pow_(eps, 2), pow_(y, 2)),
                                    mul(2, rho, sub(gam, 2), eps, y))), P(9)),
            F("zabr.B", "B(y)", "definition",
              eq(apply("B", y), add(mul(2, rho, sub(1, gam), eps),
                                    mul(2, sub(1, gam), sub(gam, 2), pow_(eps, 2), y))), P(9)),
            F("zabr.C", "C", "definition", eq(sym("C"), mul(pow_(sub(1, gam), 2), pow_(eps, 2))),
              P(9)),
            F("zabr.F", "f'(y) = F(y, f)", "definition",
              eq(apply("F", y, sym("f")), div(add(neg(mul(apply("B", y), sym("f"))), sqrt(sub(
                  mul(pow_(apply("B", y), 2), pow_(sym("f"), 2)),
                  mul(4, apply("A", y), sub(mul(sym("C"), pow_(sym("f"), 2)), 1))))),
                  mul(2, apply("A", y)))), P(9)),
            F("zabr.local_vol_zabr", "ZABR equivalent local volatility", "identity",
              eq(apply("vartheta", k), mul(z, sig(k), pow_(apply(
                  "F", y, mul(pow_(z, sub(gam, 1)), sym("x"))), -1))), P(9, "(9)"), defines=False),
        ],
        "checks": [
            {"id": "sabr-x-solves-eikonal", "kind": "sympy_identity",
             "description": "(7) solves the diffusion condition with epsilon(z) = epsilon z, "
                            "for an arbitrary sigma(s)",
             "target_ast": add(mul(pow_(z, 2), pow_(sig(s_), 2), pow_(pd(sym("x_SABR"), "s"), 2)),
                               mul(pow_(mul(eps, z), 2), pow_(pd(sym("x_SABR"), "z"), 2)),
                               mul(2, rho, z, sig(s_), mul(eps, z), pd(sym("x_SABR"), "s"),
                                   pd(sym("x_SABR"), "z"))),
             "against_ast": num(1), "abstract": ["sigma"]},
            {"id": "sabr-x-boundary", "kind": "sympy_identity",
             "description": "x(s = k, z) = 0 for (7)",
             "target_ast": sym("x_SABR"), "against_ast": num(0), "subs": {"s": "k"},
             "abstract": ["sigma"]},
            {"id": "zabr-ode-reduces-to-sabr", "kind": "sympy_identity",
             "description": "With gamma = 1 the ZABR ODE is solved by the SABR x(y) of (7)",
             "target_ast": add(mul(apply("A", y), pow_(dd(sabr_x(y), "y"), 2)),
                               mul(apply("B", y), dd(sabr_x(y), "y"), sabr_x(y)),
                               mul(sym("C"), pow_(sabr_x(y), 2))),
             "against_ast": num(1), "subs": {"gamma": 1}},
            {"id": "F-solves-ode-quadratic", "kind": "sympy_identity",
             "description": "F(y, f) is a root of A F^2 + B F f + C f^2 = 1",
             "target_ast": add(mul(apply("A", y), pow_(apply("F", y, sym("f")), 2)),
                               mul(apply("B", y), apply("F", y, sym("f")), sym("f")),
                               mul(sym("C"), pow_(sym("f"), 2))),
             "against_ast": num(1)},
            {"id": "sabr-x-integral-form", "kind": "compare",
             "description": "int_0^y J(u)^{-1} du equals the closed form in (7)",
             "target_ast": integral(div(1, Jy(u)), "u", 0, y), "against_ast": sabr_x(y),
             "inputs": {"y": 1.7, "epsilon": 0.47, "rho": -0.48}, "rel_tol": 1e-10},
            {"id": "sabr-7-close-to-hagan", "kind": "compare",
             "description": "(7) is 'basically the result of Hagan et al.': Black vol vs (2.17) "
                            "at t_ex = 0, Figure 1 parameters",
             "target": "zabr.sabr_vbar", "against": "hagan2002.sigma_B",
             "inputs": {"s": 0.05, "k": 0.08, "z": 1.0, "c": 0.0873, "beta": 0.7, "epsilon": 0.47,
                        "rho": -0.48, "f": 0.05, "K": 0.08, "alpha": 0.0873, "nu": 0.47,
                        "t_ex": 0.0}, "rel_tol": 5e-3},
            {"id": "cev-vol-gamma-one-is-sabr", "kind": "sde_reduction",
             "description": "gamma = 1 reduces the ZABR volatility SDE to SABR (2.13)",
             "target": "zabr.cev_vol_sde", "against": "hagan2002.vol_sde", "subs": {"gamma": 1},
             "rename": {"z": "alphahat", "epsilon": "nu", "Z": "W_2"}},
            {"id": "cev-forward-is-sabr-forward", "kind": "sde_reduction",
             "description": "With sigma(s) = s^beta the forward SDE is SABR's (2.13)",
             "target": "zabr.cev_spot_sde", "against": "hagan2002.forward_sde", "subs": {"c": 1},
             "rename": {"z": "alphahat", "s": "Fhat", "W": "W_1"}},
        ],
    }


# ---------------------------------------------------------------------------
# Sidani 2014: normal (arithmetic) Heston
# ---------------------------------------------------------------------------

def sidani():
    """Sidani (2014), verbatim notation: x forward, nu variance, omega vol of variance."""
    x, nu, t, tau, K = sym("x"), sym("nu"), sym("t"), sym("tau"), sym("K")
    kap, th, om, rho = sym("kappa"), sym("theta"), sym("omega"), sym("rho")
    x0, nu0, u, xi, eps = sym("x_0"), sym("nu_0"), sym("u"), sym("xi"), sym("epsilon")
    V = lambda pg, eqn=None, **kw: src(eqn, pg, verified=True, **kw)  # noqa: E731
    # --- the paper's closed form, p. 4, as printed ---------------------------------------
    a_u = sub(kap, mul(rho, om, u, I))                        # kappa - rho omega u i
    s_, g_ = apply("s", u), apply("g", u)
    Dt = lambda tt: mul(div(sub(a_u, s_), pow_(om, 2)),     # noqa: E731
                        div(sub(1, exp(mul(neg(s_), tt))), sub(1, mul(g_, exp(mul(neg(s_), tt))))))
    Ct = lambda tt: mul(div(mul(kap, th), pow_(om, 2)), sub(mul(sub(a_u, s_), tt), mul(  # noqa: E731
        2, log(div(sub(mul(g_, exp(mul(neg(s_), tt))), 1), sub(g_, 1))))))
    # --- the same model derived independently here (what Table 1 was computed with) -------
    core = sub(kap, mul(I, rho, om, u))
    Dw, Gw = apply("s_w", u), apply("g_w", u)
    eDT = exp(mul(neg(Dw), tau))
    der = dict(fidelity="derived",
               ref="Derived independently (wwmath, 2026) from model (1) by the affine method; "
                   "reproduces Sidani's Table 1")
    # payoff transform integrand for check (3)
    zc = add(neg(mul(I, eps)), xi)                           # -i eps + xi
    return {
        "paper": {"id": "sidani2014", "short": "Sidani 2014", "transcription_status": "core-complete"},
        "symbols": [
            S("x", "state", "Forward price of the asset (normal dynamics; may be negative)"),
            S("nu", "state", "Variance of changes in the level of x", domain="nonnegative"),
            S("t", "time", "Time"),
            S("tau", "time", "Time to expiry"),
            S("K", "parameter", "Strike (may be zero or negative)"),
            S("kappa", "parameter", "Speed of mean reversion of the variance"),
            S("theta", "parameter", "Long-term limit of the variance"),
            S("omega", "parameter", "Volatility of the variance"),
            S("rho", "parameter", "Correlation of W and Z"),
            S("W", "brownian_motion", "Brownian motion driving x (forward measure)"),
            S("Z", "brownian_motion", "Brownian motion driving nu"),
            S("x_0", "parameter", "Forward price today"),
            S("nu_0", "parameter", "Variance today"),
            S("x_tau", "variable", "Forward price at expiry"),
            S("u", "variable", "Fourier variable"),
            S("xi", "integration_variable", "Real part of the Fourier variable -i epsilon + xi"),
            S("epsilon", "parameter", "Small positive damping, epsilon > 0 (paper uses 1e-4)"),
            S("c", "variable", "Forward price of the call"),
            S("P", "function", "Transition density P(t, x, nu)"),
            S("Phi", "function", "Fourier transform of P in x"),
            S("C", "function", "C(t) of the Ansatz"),
            S("D", "function", "D(t) of the Ansatz"),
        ],
        "formulas": [
            F("sidani2014.forward_sde", "Normal forward dynamics", "sde",
              sde(x, (sqrt(nu), sym("W"))), V(2, "(1)"),
              notes="Differs from Heston's (1) only by the missing factor x: normal, not lognormal."),
            F("sidani2014.variance_sde", "Square-root variance (as Heston)", "sde",
              sde(nu, (mul(kap, sub(th, nu)), t), (mul(om, sqrt(nu)), sym("Z"))), V(2, "(1)")),
            F("sidani2014.correlation", "Brownian correlation", "correlation",
              eq(mul(d(sym("W")), d(sym("Z"))), mul(rho, d(t))), V(2, "(1)")),
            F("sidani2014.price_def", "Call price under the forward measure", "identity",
              eq(sym("c"), expect(call("max", sub(sym("x_tau"), K), 0))), V(2, "(2)"),
              defines=False),
            F("sidani2014.payoff_transform", "Fourier transform of the call payoff", "identity",
              eq(integral(mul(exp(neg(mul(I, zc, sym("x_tau")))), call("max", sub(sym("x_tau"), K), 0)),
                          "x_tau", neg(INF), INF),
                 neg(div(exp(mul(sub(neg(eps), mul(I, xi)), K)), pow_(zc, 2)))),
              V(2, "(3)"), defines=False, notes="Holds for every epsilon > 0."),
            F("sidani2014.phi_def", "Fourier transform of the density of x at expiry", "identity",
              eq(apply("phi", u), expect(exp(neg(mul(I, u, sym("x_tau")))))), V(2),
              defines=False, notes="phi(-u) is then the characteristic function (p. 2)."),
            F("sidani2014.c_printed", "Call price, eq. (6) as printed", "price",
              eq(sym("c_printed"), mul(div(1, PI), integral(Re(div(
                  mul(apply("phi", sub(mul(I, eps), xi)), neg(exp(mul(sub(neg(eps), mul(I, xi)), K)))),
                  pow_(zc, 2))), "xi", 0, INF))), V(3, "(6)"),
              notes="With phi as printed on p. 4 this prices the model with correlation -rho: see "
                    "the table1-* checks. The inversion itself is right (it agrees at rho = 0)."),
            F("sidani2014.phi", "phi(u) = Phi(tau, u, nu_0), as printed", "characteristic_function",
              eq(apply("phi", u), exp(add(apply("C", u), mul(apply("D", u), nu0),
                                          neg(mul(I, u, x0))))), V(4),
              notes="Ansatz Phi(t, u, nu) = exp(C(t) + D(t) nu - i u x_0), evaluated at t = tau."),
            F("sidani2014.D", "D(t), as printed, at t = tau", "definition",
              eq(apply("D", u), Dt(tau)), V(4)),
            F("sidani2014.C", "C(t), as printed, at t = tau", "definition",
              eq(apply("C", u), Ct(tau)), V(4)),
            F("sidani2014.g", "g, as printed", "definition",
              eq(g_, div(sub(a_u, s_), add(a_u, s_))), V(4)),
            F("sidani2014.s", "s, as printed", "definition",
              eq(s_, sqrt(add(pow_(a_u, 2), mul(pow_(om, 2), pow_(u, 2))))), V(4)),
            # ---- independent derivation ----
            F("sidani2014.phi_w", "Characteristic function of x_tau - x_0 (derived)",
              "characteristic_function",
              eq(apply("phi_w", u), exp(add(apply("A_w", u), mul(apply("B_w", u), nu0)))), src(**der)),
            F("sidani2014.A_w", "A(u) (derived)", "definition",
              eq(apply("A_w", u), mul(kap, th, sub(
                  neg(div(mul(pow_(u, 2), tau), add(core, Dw))),
                  mul(div(2, pow_(om, 2)), log(div(sub(1, mul(Gw, eDT)), sub(1, Gw))))))),
              src(**der),
              notes="Uses core - s = -omega^2 u^2 / (core + s) to avoid cancellation as omega -> 0."),
            F("sidani2014.B_w", "B(u) (derived)", "definition",
              eq(apply("B_w", u), neg(div(mul(pow_(u, 2), sub(1, eDT)),
                                          mul(add(core, Dw), sub(1, mul(Gw, eDT)))))), src(**der)),
            F("sidani2014.s_w", "s(u) (derived)", "definition",
              eq(Dw, sqrt(add(pow_(core, 2), mul(pow_(om, 2), pow_(u, 2))))), src(**der),
              notes="Heston's d with u^2 in place of u^2 + iu: no convexity term for normal dynamics."),
            F("sidani2014.g_w", "g(u) (derived)", "definition",
              eq(Gw, neg(div(mul(pow_(om, 2), pow_(u, 2)), pow_(add(core, Dw), 2)))), src(**der),
              notes="(core - s)/(core + s), rationalised."),
            F("sidani2014.call", "Call price (derived; reproduces Table 1)", "price",
              eq(sym("c_w"), add(div(sub(x0, K), 2), mul(div(1, PI), integral(
                  div(sub(1, Re(mul(exp(mul(I, u, sub(x0, K))), apply("phi_w", u)))), pow_(u, 2)),
                  "u", 0, INF)))), src(**der),
              notes="From E[Y^+] = E[Y]/2 + E|Y|/2 and E|Y| = (2/pi) int_0^inf (1 - Re phi_Y(u))/u^2 du."),
        ],
        "checks": [
            *[{"id": f"table1-derived-K{kk}", "kind": "compare",
               "description": f"Derived price reproduces Sidani's Table 1 (formula column) at K = {kk}",
               "target": "sidani2014.call", "expected": ev,
               "inputs": {"x_0": -0.001, "K": kk, "nu_0": 0.09, "tau": 1.0, "kappa": 1.0,
                          "theta": 0.5 * 0.001 ** 2, "omega": 0.25, "rho": -0.9},
               "abs_tol": 1e-5}
              for kk, ev in ((-0.0005, 0.09223), (0.0, 0.09194), (0.0005, 0.09166))],
            {"id": "table1-printed-finding", "kind": "compare",
             "description": "Documented finding: (6) with phi as printed misses Table 1 at K = 0 by "
                            "1.6e-4 (it prices correlation -rho); the derived formula matches Table 1",
             "target": "sidani2014.c_printed", "against": "sidani2014.call",
             "inputs": {"x_0": -0.001, "K": 0.0, "nu_0": 0.09, "tau": 1.0, "kappa": 1.0,
                        "theta": 0.5 * 0.001 ** 2, "omega": 0.25, "rho": -0.9, "epsilon": 1e-4},
             "expect_difference": [1.60e-4, 1.67e-4]},
            {"id": "table1-printed-agrees-at-rho-zero", "kind": "compare",
             "description": "At rho = 0 the printed (6) and the derived formula agree: the damped "
                            "inversion, C, D, g and s are right; only the rho term's sign differs",
             "target": "sidani2014.c_printed", "against": "sidani2014.call",
             "inputs": {"x_0": -0.001, "K": 0.0005, "nu_0": 0.09, "tau": 1.0, "kappa": 1.0,
                        "theta": 0.5 * 0.001 ** 2, "omega": 0.25, "rho": 0.0, "epsilon": 1e-4},
             "rel_tol": 1e-8, "f77": False,
             "f77_reason": "the epsilon = 1e-4 damping puts an O(epsilon)-wide peak at xi = 0 that "
                           "the F77 runtime's fixed-panel Gauss-Legendre rule cannot resolve; "
                           "Python (adaptive QUADPACK) and C++ (adaptive Gauss-Kronrod) can"},
            {"id": "riccati-9b", "kind": "sympy_identity",
             "description": "Printed D(t) solves (9b): D' - omega^2 D^2 / 2 + (kappa - rho omega u i) D + u^2/2 = 0",
             "target_ast": add(sub({"op": "Derivative", "expr": Dt(t), "var": t},
                                   mul(half, pow_(om, 2), pow_(Dt(t), 2))),
                               mul(a_u, Dt(t)), mul(half, pow_(u, 2))),
             "against_ast": num(0)},
            {"id": "riccati-9a", "kind": "sympy_identity",
             "description": "Printed C(t) solves (9a): C' - kappa theta D = 0",
             "target_ast": sub({"op": "Derivative", "expr": Ct(t), "var": t}, mul(kap, th, Dt(t))),
             "against_ast": num(0)},
            {"id": "riccati-initial", "kind": "sympy_identity",
             "description": "D(0) = C(0) = 0",
             "target_ast": add(Dt(num(0)), Ct(num(0))), "against_ast": num(0)},
            *[{"id": f"payoff-transform-{part}", "kind": "compare",
               "description": f"(3) holds: {part} part at epsilon = 0.5, xi = 1.3, K = 0.2",
               "target_ast": integral(call(part, mul(exp(neg(mul(I, zc, sym("x_tau")))),
                                                     sub(sym("x_tau"), K))), "x_tau", K, INF),
               "against_ast": call(part, neg(div(exp(mul(sub(neg(eps), mul(I, xi)), K)), pow_(zc, 2)))),
               "inputs": {"epsilon": 0.5, "xi": 1.3, "K": 0.2}, "abs_tol": 1e-10}
              for part in ("Re", "Im")],
            {"id": "bachelier-limit", "kind": "compare",
             "description": "omega -> 0 with nu = theta recovers the Bachelier price",
             "target": "sidani2014.call", "against": "bachelier1900.call",
             "bind": {"sigma": sqrt(th), "F": x0, "T": tau},
             "inputs": {"x_0": 100.0, "K": 104.0, "nu_0": 64.0, "tau": 1.0, "kappa": 1.0,
                        "theta": 64.0, "omega": 0.01, "rho": 0.0}, "rel_tol": 1e-5},
            {"id": "monte-carlo", "kind": "monte_carlo",
             "description": "Euler simulation of (1) reproduces the derived price",
             "sde": ["sidani2014.forward_sde", "sidani2014.variance_sde"],
             "correlation": ["sidani2014.correlation"], "time": "t", "horizon": "tau",
             "payoff_ast": mx(sub(x, K), 0), "against": "sidani2014.call",
             "inputs": {"x": 100.0, "nu": 64.0, "x_0": 100.0, "nu_0": 64.0, "K": 105.0, "tau": 1.0,
                        "kappa": 1.5, "theta": 81.0, "omega": 6.0, "rho": -0.5},
             "paths": 200000, "steps": 250, "seed": 6, "abs_tol": 0.03},
        ],
    }


# ---------------------------------------------------------------------------
# Alos, Bures & Vives 2026: jump-diffusion stochastic-volatility Bachelier
# ---------------------------------------------------------------------------

def alos():
    S_t, k, T, t, sg, rho = sym("S_t"), sym("k"), sym("T"), sym("t"), sym("sigma"), sym("rho")
    y, s_, u_ = sym("y"), sym("s"), sym("u")
    ttm = sub(T, t)
    dk = lambda kk, ss: apply("d", kk, ss)  # noqa: E731
    bac = lambda a1, a2, a3, a4, a5: apply("Bac", a1, a2, a3, a4, a5)  # noqa: E731
    P = lambda pg, eqn=None, **kw: src(eqn, pg, verified=True, **kw)  # noqa: E731
    nu_int = lambda region: {"op": "Integral", "integrand": y, "var": y, "lower": neg(INF),  # noqa: E731
                             "upper": INF, "measure": sym("nu"), **({"region": region} if region else {})}
    I_at = lambda kk: apply("I_t", kk)  # noqa: E731
    kst = sym("kstar_t")
    dIk = {"op": "PartialDerivative", "expr": I_at(k), "var": k, "at": kst}
    lim = lambda e: {"op": "Limit", "expr": e, "var": T, "to": t}  # noqa: E731
    malliavin = {"op": "Expectation", "given": t, "args": [
        {"op": "MalliavinDerivative", "expr": idx("sigma", u_), "at": s_}]}
    dbl = integral(integral(malliavin, "u", s_, T), "s", t, T)
    H = sym("H")
    n_, lam, muJ, dl = sym("n"), sym("lambda"), sym("mu_J"), sym("delta")
    m_n = add(S_t, mul(sub(n_, mul(lam, ttm)), muJ))
    s_n = sqrt(add(mul(pow_(sg, 2), ttm), mul(n_, pow_(dl, 2))))
    z_n = div(sub(m_n, k), s_n)
    return {
        "paper": {"id": "alos2026", "short": "Alòs, Burés & Vives 2026",
                  "transcription_status": "core-complete",
                  "pdf_version": "arXiv:2503.22282v1 (31 March 2025); page numbers are the preprint's"},
        "symbols": [
            S("S_t", "state", "Asset price at time t (S_0 > 0 fixed)"),
            S("sigma", "process", "a.s. continuous, square-integrable, F^W-adapted volatility"),
            S("rho", "parameter", "Correlation, rho in (-1, 1)"),
            S("W", "brownian_motion", "Brownian motion driving the volatility"),
            S("B", "brownian_motion", "Independent Brownian motion"),
            S("L", "levy_process", "Pure-jump Levy process with triplet (a, 0, nu)"),
            S("a", "parameter", "Drift of L"),
            S("nu", "measure", "Levy measure of L"),
            S("c_1", "parameter", "c_1 = int y nu(dy)"),
            S("c_1^epsilon", "parameter", "Truncated first moment of nu"),
            S("epsilon", "parameter", "Truncation level"),
            S("y", "integration_variable", "Jump size"),
            S("s", "integration_variable", "Time"),
            S("u", "integration_variable", "Time"),
            S("t", "time", "Current time"),
            S("T", "time", "Maturity"),
            S("k", "parameter", "Strike"),
            S("kstar_t", "variable", "ATM strike k*_t = S_t"),
            S("V_t", "variable", "Call price"),
            S("I_t", "function", "Bachelier implied volatility I_t(k)"),
            S("v_t", "variable", "Future average volatility"),
            S("Y_t", "variable", "Integrated future variance"),
            S("H", "parameter", "Hurst-type regularity exponent of Hypothesis 3"),
            S("Bac", "function", "Bachelier pricing function"),
            S("d", "function", "d(k, sigma)"),
            S("n", "index", "Number of jumps (compound-Poisson illustration)"),
            S("lambda", "parameter", "Jump intensity (compound-Poisson case, lambda = c_0)"),
            S("mu_J", "parameter", "Mean Gaussian jump size (Section 7 illustration)"),
            S("delta", "parameter", "Std. dev. of Gaussian jump size"),
            S("N_max", "parameter", "Truncation of the Poisson sum"),
            S("I", "variable", "Trial implied volatility"),
        ],
        "formulas": [
            F("alos2026.model", "Jump-diffusion stochastic-volatility Bachelier model", "sde",
              sde(S_t, (mul(sg, rho), sym("W")), (mul(sg, sqrt(sub(1, pow_(rho, 2)))), sym("B")),
                  (1, sym("L"))), P(3, "(2.1)", fidelity="restated"),
              notes="Printed in integral form S_t = S_0 + int_0^t sigma_s (rho dW_s + "
                    "sqrt(1 - rho^2) dB_s) + L_t; r = 0 throughout."),
            F("alos2026.martingale_condition", "Martingale condition on the drift of L", "identity",
              eq(sym("a"), neg(nu_int({"op": "Ge", "args": [{"op": "Abs", "args": [y]}, num(1)]}))),
              P(3), defines=False),
            F("alos2026.c_1", "c_1", "identity", eq(sym("c_1"), nu_int(None)), P(3), defines=False,
              notes="c_0 = nu(R); c_0 < infinity is the compound-Poisson case with lambda = c_0."),
            F("alos2026.c_1_eps", "c_1^epsilon", "identity",
              eq(sym("c_1^epsilon"), nu_int({"op": "Gt", "args": [{"op": "Abs", "args": [y]},
                                                                 sym("epsilon")]})),
              P(3), defines=False),
            F("alos2026.bachelier", "Bachelier call price", "price",
              eq(bac(T, t, S_t, k, sg), add(mul(sub(S_t, k), call("Phi", dk(k, sg))),
                                            mul(call("varphi", dk(k, sg)), sg, sqrt(ttm)))),
              P(5, "(3.1)")),
            F("alos2026.d", "d(k, sigma)", "definition",
              eq(dk(k, sg), div(sub(S_t, k), mul(sg, sqrt(ttm)))), P(5, "(3.1)")),
            F("alos2026.vega", "Bachelier vega", "identity",
              eq({"op": "PartialDerivative", "expr": bac(T, t, S_t, k, sg), "var": sg},
                 mul(call("varphi", dk(k, sg)), sqrt(ttm))), P(6), defines=False),
            F("alos2026.future_average_vol", "Future average volatility", "definition",
              eq(sym("v_t"), sqrt(div(sym("Y_t"), ttm))), P(6)),
            F("alos2026.Y_t", "Integrated future variance", "definition",
              eq(sym("Y_t"), integral(pow_(idx("sigma", s_), 2), "s", t, T)), P(6)),
            F("alos2026.implied_vol", "Bachelier implied volatility", "identity",
              eq(sym("V_t"), bac(T, t, S_t, k, I_at(k))), P(6), defines=False),
            F("alos2026.atm_strike", "ATM strike", "identity", eq(kst, S_t), P(6), defines=False),
            F("alos2026.level", "Theorem 3.2: ATM level", "theorem",
              eq(lim(I_at(kst)), idx("sigma", t)), P(6, "(3.2)"), defines=False,
              notes="Holds for every pure-jump Levy martingale L."),
            F("alos2026.skew", "Theorem 3.2: ATM skew, H >= 1/2", "theorem",
              eq(lim(dIk), add(div(sym("c_1"), idx("sigma", t)), lim(mul(
                  div(rho, mul(idx("sigma", t), pow_(ttm, 2))), dbl)))),
              P(6, "(3.3)"), defines=False,
              notes="Requires c_1^epsilon -> c_1 as epsilon -> 0."),
            F("alos2026.skew_rough", "Theorem 3.2: ATM skew, H < 1/2", "theorem",
              eq(lim(mul(pow_(ttm, sub(half, H)), dIk)),
                 lim(mul(div(rho, mul(idx("sigma", t), pow_(ttm, add(div(3, 2), H)))), dbl))),
              P(6, "(3.4)"), defines=False),
            F("alos2026.cp_normal_price", "Call price, constant sigma + compound-Poisson "
              "Gaussian jumps", "price",
              eq(sym("V_t"), {"op": "Sum", "var": n_, "lower": num(0), "upper": sym("N_max"),
                              "body": mul(exp(neg(mul(lam, ttm))),
                                          div(pow_(mul(lam, ttm), n_), call("factorial", n_)),
                                          add(mul(sub(m_n, k), call("Phi", z_n)),
                                              mul(s_n, call("varphi", z_n))))}),
              src(fidelity="derived",
                  ref="Conditioning on the number of jumps; the Section 7 compound-Poisson "
                      "Gaussian example with constant sigma"),
              notes="Given n jumps S_T is normal with mean S_t + (n - lambda (T-t)) mu_J and "
                    "variance sigma^2 (T-t) + n delta^2."),
            F("alos2026.cp_normal_c1", "c_1 for compound-Poisson Gaussian jumps", "definition",
              eq(sym("c_1"), mul(lam, muJ)), src(fidelity="derived"),
              notes="nu(dy) = lambda N(mu_J, delta^2)(dy)."),
        ],
        "checks": [
            {"id": "vega", "kind": "sympy_identity",
             "description": "d Bac / d sigma = varphi(d) sqrt(T - t)",
             "target_ast": {"op": "PartialDerivative", "expr": bac(T, t, S_t, k, sg), "var": sg},
             "against_ast": mul(call("varphi", dk(k, sg)), sqrt(ttm))},
            {"id": "theorem-3.2-compound-poisson", "kind": "implied_vol",
             "description": "Short maturity, constant sigma, Gaussian jumps: I -> sigma (3.2) and "
                            "dI/dk -> c_1 / sigma (3.3, D sigma = 0)",
             "price": "alos2026.cp_normal_price",
             "bachelier_ast": bac(T, t, S_t, k, sym("I")), "vol": "I", "strike": "k",
             "atm": "S_t", "bump": 1e-4,
             "expected_level_ast": sg, "expected_skew_ast": div(mul(lam, muJ), sg),
             "maturities": [1e-3, 1e-4, 1e-5],
             "inputs": {"S_t": 100.0, "t": 0.0, "sigma": 10.0, "lambda": 3.0, "mu_J": -2.0,
                        "delta": 1.0, "N_max": 30}, "rel_tol": 2e-2},
        ],
    }



# ---------------------------------------------------------------------------
# QuantLib oracle checks (research/references/quantlib.toml)
# ---------------------------------------------------------------------------

def _strike_grid(name, strikes, **fixed):
    return [{name: k, **fixed} for k in strikes]


def oracle_checks() -> dict[str, list[dict]]:
    S = sym
    black_args = {"strike": S("cstar"), "forward": S("F"), "stdDev": mul(S("s"), sqrt(S("t"))),
                  "discount": exp(mul(neg(S("r")), S("t")))}
    black_cases = ([{"F": 100.0, "cstar": k, "s": 0.25, "t": 1.0, "r": 0.03}
                    for k in (60.0, 80.0, 95.0, 100.0, 105.0, 120.0, 160.0)]
                   + [{"F": 0.035, "cstar": 0.03, "s": 0.4, "t": 10.0, "r": 0.02},
                      {"F": 50.0, "cstar": 55.0, "s": 0.05, "t": 0.02, "r": 0.0}])
    bach_args = {"strike": S("K"), "forward": S("F"), "stdDev": mul(S("sigma"), sqrt(S("T"))),
                 "discount": num(1.0)}
    bach_cases = ([{"F": 100.0, "K": k, "sigma": 12.0, "T": 0.75} for k in (70.0, 90.0, 100.0, 110.0, 140.0)]
                  + [{"F": 0.01, "K": -0.005, "sigma": 0.008, "T": 5.0}])
    sabr_args = {"strike": S("K"), "forward": S("f"), "expiryTime": S("t_ex"), "alpha": S("alpha"),
                 "beta": S("beta"), "nu": S("nu"), "rho": S("rho")}
    sabr_cases = []
    for beta, alpha, f in ((0.0, 0.0035, 0.03), (0.5, 0.035, 0.03), (0.7, 0.0873 * 0.03 ** -0.0, 0.05),
                           (1.0, 0.2, 100.0)):
        for m in (0.5, 0.8, 0.95, 1.05, 1.3, 2.0):
            for rho, nu, T in ((-0.4, 0.5, 1.0), (0.3, 0.9, 5.0)):
                sabr_cases.append({"f": f, "K": f * m, "alpha": alpha, "beta": beta, "nu": nu,
                                   "rho": rho, "t_ex": T})
    heston_args = {"s0": S("S"), "v0": S("v"), "kappa": S("kappa"), "theta": S("theta"),
                   "sigma": S("sigma"), "rho": S("rho"), "r": S("r"), "q": num(0.0),
                   "strike": S("K"), "T": S("tau")}
    heston_cases = []
    for (kap, th, sg, rho, v0) in ((1.5, 0.04, 0.3, -0.7, 0.04), (3.0, 0.09, 0.8, -0.3, 0.05),
                                   (0.5, 0.06, 0.2, 0.2, 0.03)):
        for tau in (0.2, 1.0, 2.0):
            for K in (80.0, 100.0, 125.0):
                heston_cases.append({"S": 100.0, "v": v0, "kappa": kap, "theta": th, "sigma": sg,
                                     "rho": rho, "lambda": 0.0, "r": 0.03, "K": K, "tau": tau})
    bates_args = {"s0": S("S"), "v0": S("V"), "kappa": S("betastar"),
                  "theta": div(S("alpha"), S("betastar")), "sigma": S("sigma_v"), "rho": S("rho"),
                  "r": S("r"), "q": sub(S("r"), S("b")), "lambda": S("lambdastar"),
                  "nu": sub(log(add(1, S("kbarstar"))), div(pow_(S("delta"), 2), 2)),
                  "delta": S("delta"), "strike": S("X"), "T": S("T")}
    bates_cases = []
    for (lam, kb, dl) in ((0.5, -0.1, 0.15), (2.0, 0.02, 0.05), (0.1, -0.3, 0.4)):
        for T in (0.2, 1.0):
            for X in (85.0, 100.0, 115.0):
                bates_cases.append({"S": 100.0, "V": 0.04, "T": T, "b": 0.01, "r": 0.03, "X": X,
                                    "lambdastar": lam, "kbarstar": kb, "delta": dl,
                                    "alpha": 0.06, "betastar": 1.5, "sigma_v": 0.4, "rho": -0.6})
    return {
        "black1976": [
            {"id": "quantlib-blackFormula-call", "kind": "oracle", "oracle": "ql.blackFormula",
             "description": "black1976.call vs QuantLib blackFormula (call)", "target": "black1976.call",
             "oracle_args": {**black_args, "type": "call"}, "cases": black_cases, "rel_tol": 1e-12,
             "abs_tol": 1e-14},
            {"id": "quantlib-blackFormula-put", "kind": "oracle", "oracle": "ql.blackFormula",
             "description": "black1976.put vs QuantLib blackFormula (put)", "target": "black1976.put",
             "oracle_args": {**black_args, "type": "put"}, "cases": black_cases, "rel_tol": 1e-12,
             "abs_tol": 1e-14},
        ],
        "bachelier1900": [
            {"id": "quantlib-bachelierBlackFormula-call", "kind": "oracle",
             "oracle": "ql.bachelierBlackFormula", "description": "bachelier1900.call vs QuantLib",
             "target": "bachelier1900.call", "oracle_args": {**bach_args, "type": "call"},
             "cases": bach_cases, "rel_tol": 1e-12, "abs_tol": 1e-14},
            {"id": "quantlib-bachelierBlackFormula-put", "kind": "oracle",
             "oracle": "ql.bachelierBlackFormula", "description": "bachelier1900.put vs QuantLib",
             "target": "bachelier1900.put", "oracle_args": {**bach_args, "type": "put"},
             "cases": bach_cases, "rel_tol": 1e-12, "abs_tol": 1e-14},
        ],
        "hagan2002": [
            {"id": "quantlib-sabrVolatility", "kind": "oracle", "oracle": "ql.sabrVolatility",
             "description": "(2.17) vs QuantLib unsafeSabrLogNormalVolatility, beta in {0, .5, .7, 1}, "
                            "moneyness 0.5-2, two (rho, nu, T) sets",
             "target": "hagan2002.sigma_B", "oracle_args": sabr_args, "cases": sabr_cases,
             "rel_tol": 1e-12},
        ],
        "heston1993": [
            {"id": "quantlib-AnalyticHestonEngine-trap", "kind": "oracle",
             "oracle": "ql.AnalyticHestonEngine",
             "description": "Branch-safe call vs QuantLib AnalyticHestonEngine, 3 parameter sets x "
                            "3 maturities x 3 strikes", "target": "heston1993.call_trap",
             "oracle_args": heston_args, "cases": heston_cases, "rel_tol": 1e-10, "abs_tol": 1e-10},
            {"id": "quantlib-AnalyticHestonEngine-original", "kind": "oracle",
             "oracle": "ql.AnalyticHestonEngine",
             "description": "Eq. (10) with (17) exactly as printed vs QuantLib, on the cases where the "
                            "complex log does not cross its branch cut",
             "target": "heston1993.call", "oracle_args": heston_args,
             "cases": [c for c in heston_cases if not (c["kappa"] == 1.5 and c["tau"] == 2.0)],
             "rel_tol": 1e-10, "abs_tol": 1e-10},
            {"id": "little-heston-trap-finding", "kind": "compare",
             "description": "Documented finding: at kappa=1.5, sigma=0.3, rho=-0.7, tau=2 eq. (17) as "
                            "printed crosses the log branch cut; the price differs from the "
                            "branch-safe form (which matches QuantLib to 1e-13) by 0.064",
             "target": "heston1993.call", "against": "heston1993.call_trap",
             "inputs": {"S": 100.0, "v": 0.04, "kappa": 1.5, "theta": 0.04, "sigma": 0.3,
                        "rho": -0.7, "lambda": 0.0, "r": 0.03, "K": 100.0, "tau": 2.0},
             "expect_difference": [0.063, 0.065]},
        ],
        "bates1996": [
            {"id": "quantlib-BatesEngine", "kind": "oracle", "oracle": "ql.BatesEngine",
             "description": "bates1996.call vs QuantLib BatesEngine, 3 jump regimes x 2 maturities x "
                            "3 strikes", "target": "bates1996.call", "oracle_args": bates_args,
             "cases": bates_cases, "rel_tol": 1e-7, "abs_tol": 1e-8},
        ],
    }


PAPERS = [bachelier, black, heston, bates, sabr, zabr, sidani, alos]


# ---------------------------------------------------------------------------
# As-of placement: each formula lives in the leaf of the work that published it
# ---------------------------------------------------------------------------

RENAME_WORK = {"zabr": "andreasen2011"}

# formulas (and the checks about them) that belong to a later work than the file they
# were first written in; the later leaf imports the earlier one
SPLITS = {
    "heston1993": {
        "to": "albrecher2007", "short": "Albrecher et al. 2007",
        "status": "restated-pending-pdf",
        "formulas": ["ft_j", "Ct_j", "Dt_j", "gt_j", "Pt_j", "call_trap"],
        "checks": ["trap-form-agrees-Re-1", "trap-form-agrees-Re-2", "trap-form-agrees-Im-1",
                   "trap-form-agrees-Im-2", "quantlib-AnalyticHestonEngine-trap",
                   "little-heston-trap-finding"]},
    "bachelier1900": {
        "to": "schachermayer2008", "short": "Schachermayer & Teichmann 2008",
        "status": "modern-restatement-pending-pdf",
        "formulas": ["sde", "call", "put", "d"],
        "checks": ["call-vs-payoff-integral", "put-call-parity", "modern-vs-1900-atm",
                   "monte-carlo", "quantlib-bachelierBlackFormula-call",
                   "quantlib-bachelierBlackFormula-put"]},
}

# formulas that can only be separated from a later work once the original PDF is in hand
USES_LATER_WORK = {f"bates1996.{f}": ["albrecher2007"]
                   for f in ("call", "P_1", "P_2", "psi", "A", "B", "d", "g")}


def _rename_ids(obj, mapping):
    if isinstance(obj, str):
        return mapping.get(obj, obj)
    if isinstance(obj, list):
        return [_rename_ids(x, mapping) for x in obj]
    if isinstance(obj, dict):
        return {k: (v if k.endswith("_ast") or k == "ast" else _rename_ids(v, mapping))
                for k, v in obj.items()}
    return obj


def build_all() -> dict[str, dict]:
    papers = {}
    for build in PAPERS:
        p = build()
        pid = p["paper"]["id"]
        p["paper"].pop("bib", None)
        p["symbols"] += p.pop("extra_symbols", [])
        p["formulas"] = p.pop("extra_formulas", []) + p["formulas"]
        p["checks"] = p.get("checks", []) + oracle_checks().get(pid, [])
        papers[pid] = p

    ids: dict[str, str] = {}
    for old, new in RENAME_WORK.items():
        for f in papers[old]["formulas"]:
            ids[f["id"]] = new + f["id"][len(old):]
    for src, sp in SPLITS.items():
        for f in sp["formulas"]:
            ids[f"{src}.{f}"] = f"{sp['to']}.{f}"

    for old, new in RENAME_WORK.items():
        papers[new] = papers.pop(old)
        papers[new]["paper"]["id"] = new
    for src, sp in SPLITS.items():
        p = papers[src]
        moved = [f for f in p["formulas"] if f["id"] in {f"{src}.{x}" for x in sp["formulas"]}]
        checks = [c for c in p["checks"] if c["id"] in sp["checks"]]
        p["formulas"] = [f for f in p["formulas"] if f not in moved]
        p["checks"] = [c for c in p["checks"] if c not in checks]
        from mathast import free_symbols
        still = set()
        for f in p["formulas"]:
            still |= free_symbols(f["ast"])
        used = set()
        for f in moved:
            used |= free_symbols(f["ast"])
        move_syms = [x for x in p["symbols"] if x["name"] in used and x["name"] not in still]
        p["symbols"] = [x for x in p["symbols"] if x not in move_syms]
        papers[sp["to"]] = {
            "paper": {"id": sp["to"], "short": sp["short"], "transcription_status": sp["status"],
                      "imports": [src]},
            "symbols": move_syms, "formulas": moved, "checks": checks}

    for p in papers.values():
        for f in p["formulas"]:
            f["id"] = ids.get(f["id"], f["id"])
            if f["id"] in USES_LATER_WORK:
                f["uses_later_work"] = USES_LATER_WORK[f["id"]]
        p["checks"] = [_rename_ids(c, ids) for c in p["checks"]]
    return papers


def main():
    import asof
    index = asof.leaves()
    for pid, p in build_all().items():
        leaf = index[pid]
        work = leaf["asof"]["work"]
        head = {"id": pid, "short": p["paper"]["short"],
                "transcription_status": p["paper"]["transcription_status"],
                "title": work["title"], "as_of": leaf["asof"]["as_of"]["date"]}
        if p["paper"].get("imports"):
            head["imports"] = p["paper"]["imports"]
        p["paper"] = head
        path = os.path.join(leaf["dir"], "formulas.toml")
        with open(path, "w") as fh:
            fh.write(emit(p))
        print("wrote", os.path.relpath(path, asof.REPO))


if __name__ == "__main__":
    main()
